interface Env { ALLOWED_ORIGIN: string; GITHUB_REPO: string; GITHUB_BRANCH: string; GITHUB_TOKEN: string; ADMIN_SECRET: string }
type GitHubRef = { object: { sha: string } };
type GitHubCommit = { sha: string; tree: { sha: string } };
type GitHubBlob = { sha: string; content: string; encoding: string };
type GitHubContent = { type?: string; path?: string; name?: string; sha?: string; content?: string; encoding?: string };
type WorkEntry = { id: string; name: string; code: string; path: string };
type WorkIndex = { schemaVersion: 2; works: WorkEntry[] };
type CategoryEntry = { id: string; path: string; title?: string; characters?: string[]; manufacturer?: string; quantity?: number; status?: string; cover?: string };
type CategoryIndex = { schemaVersion: 1; workId: string; category: string; items: CategoryEntry[] };
type ImageMeta = { id: string; file: string; alt?: string; isCover?: boolean; [key: string]: unknown };
type Item = { id: string; workId: string; title: string; series: string[]; characters: string[]; category: string; manufacturer: string; quantity: number; status: string; description: string; notes: string; purchase: Record<string, unknown>; arrival: Record<string, unknown>; afterSales: Record<string, unknown>; images: ImageMeta[]; [key: string]: unknown };
type ItemRef = { item: Item; path: string; categoryPath: string; workId: string };
type RemoteState = { index: WorkIndex; version: string; headSha: string; baseTreeSha: string; files: Map<string, { content: string; sha: string }>; blobs: Map<string, string>; categories: Map<string, CategoryIndex>; items: Map<string, ItemRef>; paths: Set<string> };
type WriteEntry = { path: string; content?: string; encoding?: 'utf-8' | 'base64'; sha?: string; delete?: boolean };
type AssetRequest = { path: string; content: string };

const jsonHeaders = { 'Content-Type': 'application/json; charset=utf-8' };
const MAX_ASSET_BASE64_LENGTH = 10 * 1024 * 1024;
const ASSET_RE = /^data\/[^/]+\/[a-z]\/[^/]+\/images\/[A-Za-z0-9._-]+\.(?:jpg|jpeg|png|webp|gif|avif)$/i;
const ITEM_ID_RE = /^[A-Z]{2,3}[a-z]\d{3}$/;
const CATEGORY_RE = /^[a-z]$/;
const WORK_ID_RE = /^[a-z0-9]+(?:-[a-z0-9]+)*$/;
const WORK_CODE_RE = /^[A-Z]{2,3}$/;

function response(body: unknown, status = 200, origin = '*'): Response { return new Response(JSON.stringify(body), { status, headers: { ...jsonHeaders, 'Access-Control-Allow-Origin': origin, 'Access-Control-Allow-Headers': 'Authorization, Content-Type', 'Access-Control-Allow-Methods': 'GET, POST, PUT, DELETE, OPTIONS', Vary: 'Origin' } }); }
function ok(data: unknown, origin: string): Response { return response({ ok: true, data }, 200, origin); }
function fail(code: string, message: string, status: number, origin: string): Response { return response({ ok: false, error: { code, message } }, status, origin); }
function originFor(request: Request, env: Env): string | null { const origin = request.headers.get('Origin'); return !origin || origin === env.ALLOWED_ORIGIN ? env.ALLOWED_ORIGIN : null; }
function authorized(request: Request, env: Env): boolean { return Boolean(env.ADMIN_SECRET) && request.headers.get('Authorization') === `Bearer ${env.ADMIN_SECRET}`; }
function githubHeaders(env: Env): HeadersInit { return { Accept: 'application/vnd.github+json', 'Content-Type': 'application/json', Authorization: `Bearer ${env.GITHUB_TOKEN}`, 'X-GitHub-Api-Version': '2022-11-28', 'User-Agent': 'chi-merch-api' }; }
async function githubJson<T>(env: Env, path: string, init: RequestInit = {}): Promise<T> { const res = await fetch(`https://api.github.com${path}`, { ...init, headers: { ...githubHeaders(env), ...(init.headers || {}) } }); if (!res.ok) { const detail = await res.text().catch(() => ''); const error = new Error(`GitHub request failed: ${res.status}${detail ? ` ${detail.slice(0, 240)}` : ''}`); (error as Error & { status?: number }).status = res.status; throw error; } return await res.json() as T; }
function decodeBase64(content: string): Uint8Array { const binary = atob(content.replace(/\s/g, '')); return Uint8Array.from(binary, char => char.charCodeAt(0)); }
function decodeText(content: string): string { return new TextDecoder().decode(decodeBase64(content)); }
function jsonFile(value: unknown): string { return JSON.stringify(value, null, 2) + '\n'; }
function bumpPatch(version: string): string { const m = /^(\d+)\.(\d+)\.(\d+)$/.exec(version); if (!m) throw new Error('version.json 格式無效'); return `${m[1]}.${m[2]}.${Number(m[3]) + 1}`; }
async function contents<T = GitHubContent | GitHubContent[]>(env: Env, path: string): Promise<T> { return githubJson<T>(env, `/repos/${env.GITHUB_REPO}/contents/${path}?ref=${encodeURIComponent(env.GITHUB_BRANCH)}`); }
async function readJson(env: Env, path: string, files: Map<string, { content: string; sha: string }>, paths: Set<string>): Promise<string> { const entry = await contents<GitHubContent>(env, path); if (entry.type !== 'file' || !entry.content || !entry.sha) throw new Error(`找不到資料檔：${path}`); const text = entry.encoding === 'base64' ? decodeText(entry.content) : entry.content; files.set(path, { content: text, sha: entry.sha }); paths.add(path); return text; }
async function baseRemote(env: Env): Promise<{ index: WorkIndex; version: string; headSha: string; baseTreeSha: string; files: Map<string, { content: string; sha: string }>; blobs: Map<string, string>; paths: Set<string> }> { const ref = await githubJson<GitHubRef>(env, `/repos/${env.GITHUB_REPO}/git/ref/heads/${encodeURIComponent(env.GITHUB_BRANCH)}`); const headSha = ref.object.sha; const head = await githubJson<GitHubCommit>(env, `/repos/${env.GITHUB_REPO}/git/commits/${headSha}`); const files = new Map<string, { content: string; sha: string }>(); const blobs = new Map<string, string>(); const paths = new Set<string>(); const index = JSON.parse(await readJson(env, 'data/works.json', files, paths)) as WorkIndex; const version = (JSON.parse(await readJson(env, 'public/data/version.json', files, paths)) as { version?: string }).version; if (index.schemaVersion !== 2 || !Array.isArray(index.works) || !version) throw new Error('新資料格式無效。'); return { index, version, headSha, baseTreeSha: head.tree.sha, files, blobs, paths }; }

async function loadRemoteTarget(env: Env, id: string): Promise<RemoteState> { const base = await baseRemote(env); const categories = new Map<string, CategoryIndex>(); const items = new Map<string, ItemRef>(); const work = base.index.works.find(entry => id.startsWith(entry.code)); if (!work) throw new Error(`找不到 Item 所屬作品：${id}`); const root = work.path.replace(/\/$/, ''); const dirs = await contents<GitHubContent[]>(env, root); if (!Array.isArray(dirs)) throw new Error(`作品目錄格式無效：${root}`); for (const dir of dirs.filter(x => x.type === 'dir' && typeof x.name === 'string' && CATEGORY_RE.test(x.name))) { const categoryPath = `${root}/${dir.name}/index.json`; let category: CategoryIndex; try { category = JSON.parse(await readJson(env, categoryPath, base.files, base.paths)) as CategoryIndex; } catch { continue; } if (category.schemaVersion !== 1 || category.workId !== work.id || category.category !== dir.name || !Array.isArray(category.items)) throw new Error(`類型索引格式無效：${categoryPath}`); categories.set(categoryPath, category); const summary = category.items.find(x => x.id === id); if (!summary) continue; const item = JSON.parse(await readJson(env, summary.path, base.files, base.paths)) as Item; if (item.id !== id || item.workId !== work.id || item.category !== category.category) throw new Error(`Item 索引不一致：${id}`); if (!Array.isArray(item.images)) item.images = []; items.set(id, { item, path: summary.path, categoryPath, workId: work.id }); const imageDir = `data/${work.id}/${category.category}/${id}/images`; try { const imageEntries = await contents<GitHubContent[]>(env, imageDir); if (Array.isArray(imageEntries)) for (const image of imageEntries) if (image.type === 'file' && image.path && image.sha) { base.paths.add(image.path); base.blobs.set(image.path, image.sha); } } catch { /* empty image directory */ } } if (!items.has(id)) throw new Error(`找不到 Item：${id}`); return { ...base, categories, items }; }

async function loadRemoteForNewItem(env: Env, id: string, workId: string, categoryCode: string): Promise<RemoteState> { const base = await baseRemote(env); const work = base.index.works.find(entry => entry.id === workId); if (!work) throw new Error(`找不到 Item 所屬作品：${workId}`); if (!id.startsWith(work.code)) throw new Error('Item ID 與作品代碼不一致。'); const categories = new Map<string, CategoryIndex>(); const items = new Map<string, ItemRef>(); const root = work.path.replace(/\/$/, ''); const dirs = await contents<GitHubContent[]>(env, root); if (!Array.isArray(dirs)) throw new Error(`作品目錄格式無效：${root}`); for (const dir of dirs.filter(x => x.type === 'dir' && typeof x.name === 'string' && CATEGORY_RE.test(x.name))) { const categoryPath = `${root}/${dir.name}/index.json`; try { const category = JSON.parse(await readJson(env, categoryPath, base.files, base.paths)) as CategoryIndex; if (category.schemaVersion !== 1 || category.workId !== work.id || category.category !== dir.name || !Array.isArray(category.items)) throw new Error(`類型索引格式無效：${categoryPath}`); categories.set(categoryPath, category); for (const summary of category.items) if (summary.id === id) throw new Error(`Item ID 已存在：${id}`); } catch (error) { if (error instanceof Error && error.message.startsWith('Item ID 已存在')) throw error; } } const targetPath = `data/${work.id}/${categoryCode}/index.json`; if (!categories.has(targetPath)) categories.set(targetPath, { schemaVersion: 1, workId: work.id, category: categoryCode, items: [] }); return { ...base, categories, items }; }

async function loadRemote(env: Env): Promise<RemoteState> { const base = await baseRemote(env); const tree = await githubJson<{ tree: { path?: string; type?: string; sha?: string }[]; truncated?: boolean }>(env, `/repos/${env.GITHUB_REPO}/git/trees/${base.baseTreeSha}?recursive=1`); if (tree.truncated) throw new Error('GitHub 資料樹過大，無法安全載入。'); for (const entry of tree.tree) if (entry.type === 'blob' && entry.path && entry.sha) base.blobs.set(entry.path, entry.sha); const categories = new Map<string, CategoryIndex>(); const items = new Map<string, ItemRef>(); for (const entry of base.index.works) { const prefix = `${entry.path}/`; for (const treeEntry of tree.tree.filter(x => x.type === 'blob' && x.path?.startsWith(prefix) && /^data\/[^/]+\/[a-z]\/index\.json$/.test(x.path))) { const categoryPath = treeEntry.path as string; const category = JSON.parse(await readJson(env, categoryPath, base.files, base.paths)) as CategoryIndex; categories.set(categoryPath, category); for (const summary of category.items) { const item = JSON.parse(await readJson(env, summary.path, base.files, base.paths)) as Item; if (!Array.isArray(item.images)) item.images = []; items.set(item.id, { item, path: summary.path, categoryPath, workId: entry.id }); } } } return { ...base, categories, items }; }
function allWorks(remote: RemoteState) { return remote.index.works.map(work => ({ id: work.id, name: work.name, code: work.code, items: [...remote.items.values()].filter(x => x.workId === work.id).map(x => x.item) })); }
async function dataResponse(env: Env, origin: string): Promise<Response> { const remote = await loadRemote(env); return ok({ works: allWorks(remote), version: remote.version }, origin); }

function validateItem(item: unknown): asserts item is Item { if (!item || typeof item !== 'object' || Array.isArray(item)) throw new Error('Item 必須是物件'); const v = item as Record<string, unknown>; if (typeof v.id !== 'string' || !ITEM_ID_RE.test(v.id)) throw new Error('Item ID 格式無效'); if (typeof v.workId !== 'string' || !v.workId) throw new Error('workId 為必填欄位'); if (typeof v.title !== 'string' || !v.title.trim()) throw new Error('標題為必填欄位'); if (!CATEGORY_RE.test(String(v.category || ''))) throw new Error('category 格式無效'); if (!Array.isArray(v.series) || v.series.some(x => typeof x !== 'string')) throw new Error('series 必須是字串陣列'); if (!Array.isArray(v.characters) || v.characters.some(x => typeof x !== 'string')) throw new Error('characters 必須是字串陣列'); if (typeof v.quantity !== 'number' || !Number.isInteger(v.quantity) || v.quantity < 1) throw new Error('quantity 必須是大於等於 1 的整數'); if (!Array.isArray(v.images) || v.images.some(x => !x || typeof x !== 'object' || Array.isArray(x))) throw new Error('images 格式無效'); for (const forbidden of ['workName','shipping','material','release','createdAt','updatedAt']) if (forbidden in v) throw new Error(`禁止儲存欄位：${forbidden}`); }
function normalizeImages(images: ImageMeta[]): ImageMeta[] { const files = new Set<string>(); const ids = new Set<string>(); let cover = false; return images.map(image => { if (!image.file || files.has(image.file)) throw new Error(`圖片 file 重複：${image.file}`); if (!image.id || ids.has(image.id)) throw new Error(`圖片 id 重複：${image.id}`); files.add(image.file); ids.add(image.id); if (image.isCover) { if (cover) throw new Error('一個 Item 只能有一張封面。'); cover = true; } return { ...image }; }); }
function normalizeItem(item: Item): Item { const copy = JSON.parse(JSON.stringify(item)) as Item; delete copy.workName; copy.images = normalizeImages(copy.images || []); return copy; }
function categoryEntry(item: Item, path: string): CategoryEntry { const cover = item.images.find(x => x.isCover); return { id: item.id, path, title: item.title, characters: item.characters, manufacturer: item.manufacturer, quantity: item.quantity, status: item.status, ...(cover?.file ? { cover: cover.file } : {}) }; }
async function createBlob(env: Env, content: string, encoding: 'utf-8' | 'base64' = 'utf-8'): Promise<string> { return (await githubJson<GitHubBlob>(env, `/repos/${env.GITHUB_REPO}/git/blobs`, { method: 'POST', body: JSON.stringify({ content, encoding }) })).sha; }
async function createAtomicCommit(env: Env, remote: RemoteState, writes: WriteEntry[], message: string): Promise<void> { const seen = new Set<string>(); if (!writes.length) throw new Error('寫入內容不可為空。'); for (const file of writes) { if (!file.path || seen.has(file.path)) throw new Error(`atomic write 包含重複或無效路徑：${file.path}`); seen.add(file.path); if (file.delete && (file.content !== undefined || file.sha !== undefined)) throw new Error(`刪除項目不得同時提供 content/sha：${file.path}`); } const tree = await githubJson<{ sha: string }>(env, `/repos/${env.GITHUB_REPO}/git/trees`, { method: 'POST', body: JSON.stringify({ base_tree: remote.baseTreeSha, tree: await Promise.all(writes.map(async file => ({ path: file.path, mode: '100644', type: 'blob', sha: file.delete ? null : file.sha || await createBlob(env, file.content || '', file.encoding || 'utf-8') }))) }) }); const commit = await githubJson<GitHubCommit>(env, `/repos/${env.GITHUB_REPO}/git/commits`, { method: 'POST', body: JSON.stringify({ message, tree: tree.sha, parents: [remote.headSha] }) }); try { await githubJson(env, `/repos/${env.GITHUB_REPO}/git/refs/heads/${encodeURIComponent(env.GITHUB_BRANCH)}`, { method: 'PATCH', body: JSON.stringify({ sha: commit.sha, force: false }) }); } catch (error) { if ((error as Error & { status?: number }).status === 422) throw new Error('資料在寫入期間已被其他操作更新，這次修改未套用。請重新載入後再試。'); throw error; } }

async function updateItem(env: Env, id: string, input: unknown, origin: string): Promise<Response> { const raw = (input as { item?: unknown } | null)?.item; validateItem(raw); if (raw.id !== id) return fail('ID_MISMATCH', '路由 Item ID 與 payload 不一致。', 400, origin); const existingRemote = await (async () => { try { return await loadRemoteTarget(env, id); } catch (error) { if (error instanceof Error && error.message === `找不到 Item：${id}`) return null; throw error; } })(); const remote = existingRemote || await loadRemoteForNewItem(env, id, raw.workId, raw.category); const work = remote.index.works.find(x => x.id === raw.workId); if (!work) return fail('WORK_NOT_FOUND', '找不到 Item 所屬作品。', 404, origin); const existing = remote.items.get(id); if (existing && existing.workId !== raw.workId) return fail('WORK_CHANGE', '既有 Item 不允許更換作品。', 400, origin); const item = normalizeItem(raw); const newPath = `data/${work.id}/${item.category}/${id}/data.json`; const newCategoryPath = `data/${work.id}/${item.category}/index.json`; const writes: WriteEntry[] = [{ path: newPath, content: jsonFile(item) }]; if (existing && existing.path !== newPath) { const oldPrefix = `data/${existing.workId}/${existing.item.category}/${id}/images/`; const newPrefix = `data/${work.id}/${item.category}/${id}/images/`; const oldImages = [...remote.paths].filter(p => p.startsWith(oldPrefix)); const conflicts = [...remote.paths].filter(p => p.startsWith(newPrefix)); if (conflicts.length) return fail('ITEM_MOVE_CONFLICT', '目標 Item 圖片目錄已存在，移動已取消。', 409, origin); for (const oldPath of oldImages) { const sha = remote.blobs.get(oldPath); if (!sha) return fail('ASSET_NOT_FOUND', `找不到要搬移的圖片：${oldPath}`, 409, origin); writes.push({ path: `${newPrefix}${oldPath.slice(oldPrefix.length)}`, sha }, { path: oldPath, delete: true }); } writes.push({ path: existing.path, delete: true }); const oldIndex = remote.categories.get(existing.categoryPath); if (oldIndex) writes.push({ path: existing.categoryPath, content: jsonFile({ ...oldIndex, items: oldIndex.items.filter(x => x.id !== id) }) }); }
  const nextIndex = remote.categories.get(newCategoryPath) || { schemaVersion: 1, workId: work.id, category: item.category, items: [] }; writes.push({ path: newCategoryPath, content: jsonFile({ ...nextIndex, items: [...nextIndex.items.filter(x => x.id !== id), categoryEntry(item, newPath)] }) }); const changed = !existing || JSON.stringify(existing.item) !== JSON.stringify(item) || existing.path !== newPath; if (changed) writes.push({ path: 'public/data/version.json', content: jsonFile({ version: bumpPatch(remote.version) }) }); await createAtomicCommit(env, remote, writes, `${existing ? 'fix: update' : 'feat: add'} item ${id}`); return dataResponse(env, origin); }

async function deleteItem(env: Env, id: string, origin: string): Promise<Response> { const remote = await loadRemoteTarget(env, id); const existing = remote.items.get(id) as ItemRef; const writes: WriteEntry[] = [{ path: existing.path, delete: true }]; const category = remote.categories.get(existing.categoryPath); if (category) writes.push({ path: existing.categoryPath, content: jsonFile({ ...category, items: category.items.filter(x => x.id !== id) }) }); const prefix = `data/${existing.workId}/${existing.item.category}/${id}/images/`; for (const p of remote.paths) if (p.startsWith(prefix)) writes.push({ path: p, delete: true }); writes.push({ path: 'public/data/version.json', content: jsonFile({ version: bumpPatch(remote.version) }) }); await createAtomicCommit(env, remote, writes, `fix: delete item ${id}`); return dataResponse(env, origin); }

function assetParts(path: string) { const m = /^data\/([^/]+)\/([a-z])\/([^/]+)\/images\/([^/]+)$/.exec(path); return m ? { workId: m[1], category: m[2], itemId: m[3], file: m[4] } : null; }
function validateAssetPath(path: unknown): string { if (typeof path !== 'string' || !ASSET_RE.test(path) || path.includes('..')) throw new Error('圖片路徑格式無效。'); return path; }
function validateAssetPayload(value: unknown): AssetRequest { if (!value || typeof value !== 'object' || Array.isArray(value)) throw new Error('圖片請求格式無效。'); const v = value as Record<string, unknown>; const path = validateAssetPath(v.path); if (typeof v.content !== 'string' || !v.content) throw new Error('圖片內容為必填欄位。'); if (v.content.length > MAX_ASSET_BASE64_LENGTH) throw new Error('圖片檔案過大，請使用 10 MB 以下的圖片。'); const content = v.content.replace(/\s/g, ''); if (!/^[A-Za-z0-9+/]*={0,2}$/.test(content)) throw new Error('圖片內容不是有效的 Base64。'); return { path, content }; }
function assetContentType(path: string): string { const ext = path.toLowerCase().split('.').pop(); return ext === 'png' ? 'image/png' : ext === 'gif' ? 'image/gif' : ext === 'webp' ? 'image/webp' : ext === 'avif' ? 'image/avif' : 'image/jpeg'; }
async function getAsset(env: Env, path: string, origin: string): Promise<Response> { const parts = assetParts(path); if (!parts) return fail('INVALID_ASSET_PATH', '圖片路徑格式無效。', 400, origin); const remote = await loadRemoteTarget(env, parts.itemId); const entry = remote.items.get(parts.itemId); if (!entry || entry.workId !== parts.workId || entry.item.category !== parts.category) return fail('ITEM_PATH_MISMATCH', '圖片路徑與 Item 所屬位置不一致。', 400, origin); if (!remote.paths.has(path)) return fail('ASSET_NOT_FOUND', '找不到圖片。', 404, origin); const blob = await githubJson<GitHubBlob>(env, `/repos/${env.GITHUB_REPO}/contents/${path}?ref=${encodeURIComponent(env.GITHUB_BRANCH)}`); return new Response(decodeBase64(blob.content), { status: 200, headers: { 'Content-Type': assetContentType(path), 'Cache-Control': 'public, max-age=31536000, immutable', 'Access-Control-Allow-Origin': origin, Vary: 'Origin', ETag: `"${blob.sha}"` } }); }
async function getAssetByFile(env: Env, file: string, origin: string): Promise<Response> { if (!/^[A-Za-z0-9._-]+\.(?:jpg|jpeg|png|webp|gif|avif)$/i.test(file)) return fail('INVALID_ASSET_PATH', '圖片檔名格式無效。', 400, origin); const remote = await loadRemote(env); const matches: string[] = []; for (const ref of remote.items.values()) { if (ref.item.images.some(image => image.file === file)) matches.push(`data/${ref.workId}/${ref.item.category}/${ref.item.id}/images/${file}`); } if (matches.length === 0) return fail('ASSET_NOT_FOUND', '找不到圖片。', 404, origin); if (matches.length > 1) return fail('ASSET_AMBIGUOUS', '圖片檔名不唯一。', 409, origin); return getAsset(env, matches[0], origin); }
async function putAsset(env: Env, asset: AssetRequest, origin: string): Promise<Response> { const parts = assetParts(asset.path); if (!parts) return fail('INVALID_ASSET_PATH', '圖片路徑格式無效。', 400, origin); const remote = await loadRemoteTarget(env, parts.itemId); const entry = remote.items.get(parts.itemId); if (!entry || entry.workId !== parts.workId || entry.item.category !== parts.category) return fail('ITEM_PATH_MISMATCH', '圖片路徑與 Item 所屬位置不一致。', 400, origin); const exists = remote.paths.has(asset.path); const item = normalizeItem(entry.item); const images = [...item.images]; if (!images.some(x => x.file === parts.file)) images.push({ id: `${parts.itemId}-${Date.now()}`, file: parts.file }); item.images = images; const category = remote.categories.get(entry.categoryPath); if (!category) return fail('CATEGORY_NOT_FOUND', '找不到圖片所屬類型索引。', 404, origin); const writes: WriteEntry[] = [{ path: asset.path, content: asset.content, encoding: 'base64' }, { path: entry.path, content: jsonFile(item) }, { path: entry.categoryPath, content: jsonFile({ ...category, items: [...category.items.filter(x => x.id !== item.id), categoryEntry(item, entry.path)] }) }]; if (!exists) writes.push({ path: 'public/data/version.json', content: jsonFile({ version: bumpPatch(remote.version) }) }); await createAtomicCommit(env, remote, writes, `${exists ? 'fix: replace' : 'feat: add'} image ${parts.itemId}/${parts.file}`); return ok({ path: asset.path, replaced: exists, version: exists ? remote.version : bumpPatch(remote.version) }, origin); }
async function deleteAsset(env: Env, path: string, origin: string): Promise<Response> { const parts = assetParts(path); if (!parts) return fail('INVALID_ASSET_PATH', '圖片路徑格式無效。', 400, origin); const remote = await loadRemoteTarget(env, parts.itemId); const entry = remote.items.get(parts.itemId); if (!entry || entry.workId !== parts.workId || entry.item.category !== parts.category) return fail('ITEM_PATH_MISMATCH', '圖片路徑與 Item 所屬位置不一致。', 400, origin); if (!remote.paths.has(path)) return fail('ASSET_NOT_FOUND', '找不到要刪除的圖片。', 404, origin); const item = normalizeItem(entry.item); item.images = item.images.filter(x => x.file !== parts.file); const category = remote.categories.get(entry.categoryPath); if (!category) return fail('CATEGORY_NOT_FOUND', '找不到圖片所屬類型索引。', 404, origin); const writes: WriteEntry[] = [{ path, delete: true }, { path: entry.path, content: jsonFile(item) }, { path: entry.categoryPath, content: jsonFile({ ...category, items: [...category.items.filter(x => x.id !== item.id), categoryEntry(item, entry.path)] }) }, { path: 'public/data/version.json', content: jsonFile({ version: bumpPatch(remote.version) }) }]; await createAtomicCommit(env, remote, writes, `fix: delete image ${parts.itemId}/${parts.file}`); return ok({ path, deleted: true, version: bumpPatch(remote.version) }, origin); }
async function cleanupAssets(env: Env, origin: string): Promise<Response> { const remote = await loadRemote(env); const referenced = new Set<string>(); for (const ref of remote.items.values()) for (const image of ref.item.images) referenced.add(`data/${ref.workId}/${ref.item.category}/${ref.item.id}/images/${image.file}`); const orphaned = [...remote.paths].filter(p => /^data\/[^/]+\/[a-z]\/[^/]+\/images\//.test(p) && !referenced.has(p)); if (!orphaned.length) return ok({ deleted: 0, version: remote.version }, origin); const writes: WriteEntry[] = orphaned.map(path => ({ path, delete: true })); const version = bumpPatch(remote.version); writes.push({ path: 'public/data/version.json', content: jsonFile({ version }) }); await createAtomicCommit(env, remote, writes, `fix: cleanup ${orphaned.length} orphan images`); return ok({ deleted: orphaned.length, version }, origin); }

function validateWork(input: unknown, requireId: boolean): { id?: string; name: string; code: string } { if (!input || typeof input !== 'object' || Array.isArray(input)) throw new Error('作品資料格式無效。'); const v = input as Record<string, unknown>; const id = typeof v.id === 'string' ? v.id.trim() : ''; const name = typeof v.name === 'string' ? v.name.trim() : ''; const code = typeof v.code === 'string' ? v.code.trim().toUpperCase() : ''; if (requireId && !WORK_ID_RE.test(id)) throw new Error('作品 ID 格式無效。'); if (!requireId && id) throw new Error('編輯作品時不可修改作品 ID。'); if (!name) throw new Error('作品名稱為必填欄位。'); if (!WORK_CODE_RE.test(code)) throw new Error('作品代碼必須是 2～3 碼大寫英文字母。'); return { ...(id ? { id } : {}), name, code }; }
async function createWork(env: Env, input: unknown, origin: string): Promise<Response> { const work = validateWork((input as { work?: unknown } | null)?.work, true); const remote = await loadRemote(env); if (remote.index.works.some(x => x.id === work.id)) return fail('WORK_EXISTS', '作品 ID 已存在。', 409, origin); if (remote.index.works.some(x => x.code === work.code)) return fail('WORK_CODE_EXISTS', '作品代碼已存在。', 409, origin); const entry = { id: work.id as string, name: work.name, code: work.code, path: `data/${work.id}` }; const index = { ...remote.index, works: [...remote.index.works, entry] }; const version = bumpPatch(remote.version); await createAtomicCommit(env, remote, [{ path: 'data/works.json', content: jsonFile(index) }, { path: 'public/data/version.json', content: jsonFile({ version }) }], `feat: add work ${entry.id}`); return dataResponse(env, origin); }
async function updateWork(env: Env, id: string, input: unknown, origin: string): Promise<Response> { const work = validateWork((input as { work?: unknown } | null)?.work, false); const remote = await loadRemote(env); const current = remote.index.works.find(x => x.id === id); if (!current) return fail('WORK_NOT_FOUND', '找不到作品。', 404, origin); if (remote.index.works.some(x => x.code === work.code && x.id !== id)) return fail('WORK_CODE_EXISTS', '作品代碼已存在。', 409, origin); const hasItems = [...remote.items.values()].some(x => x.workId === id); if (hasItems && work.code !== current.code) return fail('WORK_CODE_LOCKED', '作品已有收藏，不可修改作品代碼。', 409, origin); const index = { ...remote.index, works: remote.index.works.map(x => x.id === id ? { ...x, name: work.name, code: work.code } : x) }; const version = bumpPatch(remote.version); await createAtomicCommit(env, remote, [{ path: 'data/works.json', content: jsonFile(index) }, { path: 'public/data/version.json', content: jsonFile({ version }) }], `fix: update work ${id}`); return dataResponse(env, origin); }
async function deleteWork(env: Env, id: string, origin: string): Promise<Response> { const remote = await loadRemote(env); const current = remote.index.works.find(x => x.id === id); if (!current) return fail('WORK_NOT_FOUND', '找不到作品。', 404, origin); if ([...remote.items.values()].some(x => x.workId === id)) return fail('WORK_NOT_EMPTY', '作品仍有收藏，請先移除所有收藏後再刪除。', 409, origin); const index = { ...remote.index, works: remote.index.works.filter(x => x.id !== id) }; const version = bumpPatch(remote.version); await createAtomicCommit(env, remote, [{ path: 'data/works.json', content: jsonFile(index) }, { path: 'public/data/version.json', content: jsonFile({ version }) }], `fix: delete work ${id}`); return dataResponse(env, origin); }

export default { async fetch(request: Request, env: Env): Promise<Response> { const origin = originFor(request, env); if (!origin) return fail('ORIGIN_NOT_ALLOWED', '來源網域不被允許。', 403, '*'); if (request.method === 'OPTIONS') return response({}, 204, origin); const url = new URL(request.url); try { if (url.pathname === '/api/auth/status' && request.method === 'GET') return ok({ authenticated: authorized(request, env) }, origin); if (url.pathname === '/api/data' && request.method === 'GET') return dataResponse(env, origin);
      const workMatch = url.pathname.match(/^\/api\/works\/([^/]+)$/); if (workMatch) { if (!authorized(request, env)) return fail('UNAUTHORIZED', '需要管理員權限。', 401, origin); const id = decodeURIComponent(workMatch[1]); if (request.method === 'PUT') return updateWork(env, id, await request.json(), origin); if (request.method === 'DELETE') return deleteWork(env, id, origin); }
      if (url.pathname === '/api/works' && request.method === 'POST') { if (!authorized(request, env)) return fail('UNAUTHORIZED', '需要管理員權限。', 401, origin); return createWork(env, await request.json(), origin); }
      const itemMatch = url.pathname.match(/^\/api\/items\/([^/]+)$/); if (itemMatch) { if (!authorized(request, env)) return fail('UNAUTHORIZED', '需要管理員權限。', 401, origin); const id = decodeURIComponent(itemMatch[1]); if (request.method === 'PUT') return updateItem(env, id, await request.json(), origin); if (request.method === 'DELETE') return deleteItem(env, id, origin); }
      if (url.pathname === '/api/assets/cleanup' && request.method === 'POST') { if (!authorized(request, env)) return fail('UNAUTHORIZED', '需要管理員權限。', 401, origin); return cleanupAssets(env, origin); }
      const byFile = url.pathname.match(/^\/api\/assets\/by-file\/([^/]+)$/); if (byFile && request.method === 'GET') return getAssetByFile(env, decodeURIComponent(byFile[1]), origin);
      const assetPath = url.pathname.startsWith('/api/assets/') ? decodeURIComponent(url.pathname.slice('/api/assets/'.length)) : ''; if (assetPath) { if (request.method === 'GET') return getAsset(env, validateAssetPath(assetPath), origin); if (!authorized(request, env)) return fail('UNAUTHORIZED', '需要管理員權限。', 401, origin); if (request.method === 'PUT') return putAsset(env, validateAssetPayload(await request.json()), origin); if (request.method === 'DELETE') return deleteAsset(env, validateAssetPath(assetPath), origin); }
      return fail('NOT_FOUND', 'API 路由不存在。', 404, origin);
    } catch (error) { console.error(error); return fail('INTERNAL_ERROR', error instanceof Error ? error.message : '伺服器處理失敗。', 500, origin); } } };
