from pathlib import Path

# API validation fix
p=Path('src/api.ts'); s=p.read_text(); old="return { works: value.works as Work[], version: value.version };"; new="return { works: value.works as Work[], version: value.version, shipping: value.shipping as StoreState['shipping'] };"; assert old in s; p.write_text(s.replace(old,new,1))

# Ensure the shipping module exists.
Path('src/shipping.ts').write_text(r'''import './shipping.css';
import { deleteShipping, putShipping } from './api';
import { getStore, type MerchStore } from './store';
import type { Item, ShippingRecord } from './types';
import { escapeHtml, qs } from './utils/dom';
import { showToast } from './utils/toast';
let storeRef: MerchStore | null = null;
let editingId = '';
const allItems=()=>storeRef?.snapshot.items??[];
const money=(n:number,c:string)=>`${c||'TWD'} ${new Intl.NumberFormat('zh-TW').format(n)}`;
function render(){const root=qs<HTMLElement>('#shipping-root');if(!root||!storeRef)return;const records=storeRef.snapshot.shipping??[];const selected=records.find(x=>x.id===editingId);root.innerHTML=`<div class="shipping-layout"><section class="shipping-editor"><div class="panel-heading"><div><span class="panel-label">SHIPPING RECORD</span><h2>${selected?'編輯運費':'新增運費'}</h2></div></div><form id="shipping-form"><label>金額<input id="shipping-amount" type="number" min="0" step="0.01" required value="${selected?.amount??''}"></label><label>幣別<input id="shipping-currency" value="${escapeHtml(selected?.currency??'TWD')}" required></label><label>日期<input id="shipping-date" type="date" value="${escapeHtml(selected?.date??'')}"></label><label>物流／平台<input id="shipping-carrier" value="${escapeHtml(selected?.carrier??'')}"></label><label>備註<textarea id="shipping-note">${escapeHtml(selected?.note??'')}</textarea></label><div><strong>關聯周邊</strong><div class="shipping-items">${allItems().map(i=>`<label class="shipping-item"><input type="checkbox" value="${escapeHtml(i.id)}" ${selected?.itemIds.includes(i.id)?'checked':''}><span>${escapeHtml(i.id)} · ${escapeHtml(i.title)}</span></label>`).join('')||'<span class="muted">目前沒有周邊。</span>'}</div></div><div class="shipping-actions"><button class="button" type="submit">${selected?'儲存修改':'新增運費'}</button>${selected?'<button class="button secondary" type="button" id="shipping-cancel">取消</button>':''}</div></form></section><section class="shipping-list"><div class="panel-heading"><div><span class="panel-label">RECORDS</span><h2>運費紀錄</h2></div></div>${records.length?records.map(r=>`<article class="shipping-card"><div><strong>${escapeHtml(money(r.amount,r.currency))}</strong><span>${escapeHtml(r.date||'未填日期')}</span></div><p>${escapeHtml(r.carrier||'未設定物流')}${r.note?` · ${escapeHtml(r.note)}`:''}</p><small>關聯 ${r.itemIds.length} 件周邊</small><div class="shipping-card-actions"><button class="button secondary" type="button" data-shipping-edit="${escapeHtml(r.id)}">編輯</button><button class="button danger" type="button" data-shipping-delete="${escapeHtml(r.id)}">刪除</button></div></article>`).join(''):'<div class="empty-state">目前沒有運費紀錄。</div>'}</section></div>`;}
async function save(e:Event){e.preventDefault();if(!storeRef)return;const amount=Number(qs<HTMLInputElement>('#shipping-amount')?.value);const currency=qs<HTMLInputElement>('#shipping-currency')?.value.trim()||'TWD';const itemIds=[...document.querySelectorAll<HTMLInputElement>('#shipping-form input[type="checkbox"]:checked')].map(x=>x.value);if(!Number.isFinite(amount)||amount<0||!itemIds.length){showToast('請輸入有效運費，並至少選擇一個周邊。','error');return;}const record:ShippingRecord={id:editingId||`ship-${Date.now().toString(36)}`,amount,currency,date:qs<HTMLInputElement>('#shipping-date')?.value||undefined,carrier:qs<HTMLInputElement>('#shipping-carrier')?.value.trim()||undefined,note:qs<HTMLTextAreaElement>('#shipping-note')?.value.trim()||undefined,itemIds};try{await putShipping(record);editingId='';showToast('運費紀錄已儲存。','success')}catch(e){showToast(e instanceof Error?e.message:'儲存運費失敗。','error')}}
function bind(){const root=qs<HTMLElement>('#shipping-root');if(!root)return;root.addEventListener('submit',save);root.addEventListener('click',async e=>{const t=e.target as Element;const edit=t.closest<HTMLElement>('[data-shipping-edit]');if(edit){editingId=edit.dataset.shippingEdit||'';render();return}const del=t.closest<HTMLElement>('[data-shipping-delete]');if(del&&confirm('確定刪除此筆運費紀錄？')){try{await deleteShipping(del.dataset.shippingDelete||'');showToast('運費紀錄已刪除。','success')}catch(e){showToast(e instanceof Error?e.message:'刪除運費失敗。','error')}}if(t.closest('#shipping-cancel')){editingId='';render()}})}
async function init(){storeRef=await getStore();storeRef.subscribe(()=>{render()});render();bind()}
void init();
''')
Path('src/shipping.css').write_text('.shipping-layout{display:grid;grid-template-columns:minmax(320px,.8fr) minmax(360px,1.2fr);gap:20px}.shipping-editor,.shipping-list{background:var(--panel,#fff);border:1px solid var(--border,#ddd);border-radius:18px;padding:22px}.shipping-editor form{display:grid;gap:14px}.shipping-editor label{display:grid;gap:6px;font-weight:600}.shipping-editor input,.shipping-editor textarea{width:100%;box-sizing:border-box;padding:10px 12px;border:1px solid var(--border,#ddd);border-radius:10px;background:transparent;color:inherit}.shipping-editor textarea{min-height:80px}.shipping-items{display:grid;gap:8px;margin-top:8px;max-height:280px;overflow:auto}.shipping-item{display:flex!important;align-items:center;gap:8px;padding:9px 10px;border:1px solid var(--border,#ddd);border-radius:10px;font-weight:400!important}.shipping-item input{width:auto}.shipping-actions,.shipping-card-actions{display:flex;gap:8px}.shipping-list{display:grid;align-content:start;gap:10px}.shipping-card{border:1px solid var(--border,#ddd);border-radius:14px;padding:14px}.shipping-card>div:first-child{display:flex;justify-content:space-between;gap:10px}.shipping-card p{margin:7px 0}.shipping-card small{display:block;margin-bottom:10px}.shipping-card-actions{justify-content:flex-end}@media(max-width:900px){.shipping-layout{grid-template-columns:1fr}}')

# Store: make remote data carry shipping and initialize it, without changing existing write methods.
p=Path('src/store.ts'); s=p.read_text();
s=s.replace("constructor(state: StoreState) { this.state = cloneAndFreeze(state); }","constructor(state: StoreState) { this.state = cloneAndFreeze(state); }",1)
s=s.replace("replaceData(works: Work[], version: string): void {","replaceData(works: Work[], version: string, shipping: StoreState['shipping'] = this.state.shipping): void {",1)
s=s.replace("version, loading: false, error: null });","version, shipping, loading: false, error: null });",1)
s=s.replace("private applyRemote(data: { works: Work[]; version: string }): void { this.replaceData(data.works, data.version); }","private applyRemote(data: { works: Work[]; version: string; shipping: StoreState['shipping'] }): void { this.replaceData(data.works, data.version, data.shipping); }",1)
s=s.replace("version: '0.0.0', ui:","version: '0.0.0', shipping: [], ui:",1)
p.write_text(s)
print('pass2 complete')
