from pathlib import Path
import re
p=Path('worker/src/index.ts'); s=p.read_text()
if 'type ShippingRecord' not in s:
    s=s.replace("type AssetRequest = { path: string; content: string };", "type AssetRequest = { path: string; content: string };\ntype ShippingRecord = { id: string; amount: number; currency: string; date?: string; carrier?: string; note?: string; itemIds: string[] };\ntype ShippingData = { schemaVersion: 1; records: ShippingRecord[] };",1)
s=s.replace("type RemoteState = { index: WorkIndex; version: string; headSha:", "type RemoteState = { index: WorkIndex; version: string; shipping: ShippingRecord[]; headSha:",1)
needle="if (index.schemaVersion !== 2 || !Array.isArray(index.works) || !version) throw new Error('新資料格式無效。'); return { index, version, headSha: head.object.sha, baseTreeSha: head.tree.sha, files, blobs, paths };"
# Current source uses headSha variable; handle the actual variant.
if needle not in s:
    needle="if (index.schemaVersion !== 2 || !Array.isArray(index.works) || !version) throw new Error('新資料格式無效。'); return { index, version, headSha, baseTreeSha: head.tree.sha, files, blobs, paths };"
replacement="if (index.schemaVersion !== 2 || !Array.isArray(index.works) || !version) throw new Error('新資料格式無效。'); let shipping: ShippingRecord[] = []; try { const parsed = JSON.parse(await readJson(env, 'public/data/shipping.json', files, paths)) as ShippingData; if (parsed.schemaVersion === 1 && Array.isArray(parsed.records)) shipping = parsed.records; } catch {} return { index, version, shipping, headSha, baseTreeSha: head.tree.sha, files, blobs, paths };"
if needle in s and 'let shipping: ShippingRecord[]' not in s:
    s=s.replace(needle,replacement,1)
old="async function dataResponse(env: Env, origin: string): Promise<Response> { const remote = await loadRemote(env); return ok({ works: allWorks(remote), version: remote.version }, origin); }"
if old in s and 'function validateShipping(' not in s:
    new=old+"\nfunction validateShipping(value: unknown, remote: RemoteState): ShippingRecord { if (!value || typeof value !== 'object' || Array.isArray(value)) throw new Error('運費紀錄格式無效。'); const v=value as Record<string,unknown>; if(typeof v.id!=='string'||!/^[A-Za-z0-9_-]+$/.test(v.id)) throw new Error('運費 ID 格式無效。'); if(typeof v.amount!=='number'||!Number.isFinite(v.amount)||v.amount<0) throw new Error('運費金額無效。'); if(typeof v.currency!=='string'||!v.currency.trim()) throw new Error('運費幣別為必填。'); if(v.date!==undefined&&typeof v.date!=='string') throw new Error('運費日期無效。'); if(v.carrier!==undefined&&typeof v.carrier!=='string') throw new Error('物流欄位無效。'); if(v.note!==undefined&&typeof v.note!=='string') throw new Error('備註欄位無效。'); if(!Array.isArray(v.itemIds)||v.itemIds.length===0||v.itemIds.some(x=>typeof x!=='string')) throw new Error('至少需要一個關聯周邊。'); const ids=[...new Set(v.itemIds as string[])]; for(const id of ids) if(!remote.items.has(id)) throw new Error(`找不到關聯周邊：${id}`); return { id:v.id as string, amount:v.amount as number, currency:(v.currency as string).trim(), ...(typeof v.date==='string'&&v.date?{date:v.date}:{}), ...(typeof v.carrier==='string'&&v.carrier.trim()?{carrier:v.carrier.trim()}:{}), ...(typeof v.note==='string'&&v.note.trim()?{note:v.note.trim()}:{}), itemIds:ids }; }\nasync function shippingResponse(env: Env, origin: string): Promise<Response> { const remote=await baseRemote(env); return ok(remote.shipping,origin); }\nasync function upsertShipping(env: Env, input: unknown, origin: string): Promise<Response> { const remote=await loadRemote(env); const record=validateShipping((input as {shipping?:unknown}|null)?.shipping,remote); const exists=remote.shipping.some(x=>x.id===record.id); const records=[...remote.shipping.filter(x=>x.id!==record.id),record]; const version=bumpPatch(remote.version); await createAtomicCommit(env,remote,[{path:'public/data/shipping.json',content:jsonFile({schemaVersion:1,records})},{path:'public/data/version.json',content:jsonFile({version})}],`${exists?'fix':'feat'}: ${exists?'update':'add'} shipping ${record.id}`); return dataResponse(env,origin); }\nasync function removeShipping(env: Env, id: string, origin: string): Promise<Response> { const remote=await loadRemote(env); if(!remote.shipping.some(x=>x.id===id)) return fail('SHIPPING_NOT_FOUND','找不到運費紀錄。',404,origin); const records=remote.shipping.filter(x=>x.id!==id); const version=bumpPatch(remote.version); await createAtomicCommit(env,remote,[{path:'public/data/shipping.json',content:jsonFile({schemaVersion:1,records})},{path:'public/data/version.json',content:jsonFile({version})}],`fix: delete shipping ${id}`); return dataResponse(env,origin); }"
    s=s.replace(old,new,1)
route="if (url.pathname === '/api/data' && request.method === 'GET') return dataResponse(env, origin);"
if route in s and "/api/shipping" not in s:
    ins=route+" if (url.pathname === '/api/shipping' && request.method === 'GET') return shippingResponse(env, origin); const shippingMatch=url.pathname.match(/^\\/api\\/shipping\\/([^/]+)$/); if(shippingMatch){ if(!authorized(request,env)) return fail('UNAUTHORIZED','需要管理員驗證。',401,origin); const id=decodeURIComponent(shippingMatch[1]); if(request.method==='PUT') return upsertShipping(env,await request.json(),origin); if(request.method==='DELETE') return removeShipping(env,id,origin); } if(url.pathname==='/api/shipping'&&request.method==='POST'){ if(!authorized(request,env)) return fail('UNAUTHORIZED','需要管理員驗證。',401,origin); return upsertShipping(env,await request.json(),origin); }"
    s=s.replace(route,ins,1)
p.write_text(s)
print('worker shipping patch complete')
