import type { Item, StoreState, Work } from './types';
import { dataError } from './error';

type ApiResponse = { ok: boolean; data?: unknown; error?: { code?: string; message?: string } };
type ApiData = Pick<StoreState, 'works' | 'version' | 'shipping'>;
type ImportMetaWithEnv = ImportMeta & { env?: { VITE_MERCH_API_URL?: string } };
type AuthStatus = { authenticated: boolean };
type ApiFailure = { apiCode?: string; status: number };
type AssetResult = { path: string; replaced: boolean; version: string };
type MutationResult = { version: string };
type AssetDeleteResult = { path: string; deleted: boolean; version: string };
type WorkPayload = { id?: string; name: string; code: string };

const meta = import.meta as ImportMetaWithEnv;
const API_BASE = (meta.env?.VITE_MERCH_API_URL || '/api').replace(/\/$/, '');
const API_TIMEOUT_MS = 12_000;
const FORBIDDEN_STORAGE_FIELDS = ['workName', 'shipping', 'material', 'release', 'createdAt', 'updatedAt'] as const;
function endpoint(path: string): string { return `${API_BASE}${path.startsWith('/') ? path : `/${path}`}`; }
function authToken(): string { try { return sessionStorage.getItem('merch-admin-secret') || ''; } catch { return ''; } }
function toStorageItem(item: Item): Item { const copy = structuredClone(item) as Item & Record<string, unknown>; for (const field of FORBIDDEN_STORAGE_FIELDS) delete copy[field]; return copy; }
async function request(path: string, init: RequestInit = {}): Promise<unknown> { const headers = new Headers(init.headers); headers.set('Accept', 'application/json'); if (init.body) headers.set('Content-Type', 'application/json'); const token = authToken(); if (token) headers.set('Authorization', `Bearer ${token}`); const controller = new AbortController(); const timer = window.setTimeout(() => controller.abort(), API_TIMEOUT_MS); let response: Response; try { response = await fetch(endpoint(path), { ...init, headers, cache: 'no-store', signal: controller.signal }); } catch (error) { if (error instanceof DOMException && error.name === 'AbortError') throw dataError('API 請求逾時，請稍後再試。'); throw dataError('API 網路連線失敗，請稍後再試。'); } finally { window.clearTimeout(timer); } let payload: ApiResponse | null = null; try { payload = await response.json() as ApiResponse; } catch {} if (!response.ok || !payload?.ok) { const failure: ApiFailure = { apiCode: payload?.error?.code, status: response.status }; throw dataError(payload?.error?.message || `API 請求失敗（${response.status}）`, failure); } return payload.data; }
function isRecord(value: unknown): value is Record<string, unknown> { return Boolean(value) && typeof value === 'object' && !Array.isArray(value); }
function isStringArray(value: unknown): value is string[] { return Array.isArray(value) && value.every(item => typeof item === 'string'); }
function validateImage(value: unknown): void { if (!isRecord(value) || typeof value.id !== 'string' || !value.id.trim() || typeof value.file !== 'string' || !value.file.trim()) throw dataError('API 回傳圖片資料格式無效。'); if (value.alt !== undefined && typeof value.alt !== 'string') throw dataError('API 回傳圖片資料格式無效。'); if (value.isCover !== undefined && typeof value.isCover !== 'boolean') throw dataError('API 回傳圖片資料格式無效。'); if (value.sha !== undefined && typeof value.sha !== 'string') throw dataError('API 回傳圖片資料格式無效。'); if (value.url !== undefined && typeof value.url !== 'string') throw dataError('API 回傳圖片資料格式無效。'); if (value.path !== undefined && typeof value.path !== 'string') throw dataError('API 回傳圖片資料格式無效。'); }
function validateItem(value: unknown): value is Item { if (!isRecord(value) || typeof value.id !== 'string' || !value.id.trim() || typeof value.workId !== 'string' || !value.workId.trim() || typeof value.title !== 'string' || !isStringArray(value.series) || !isStringArray(value.characters) || typeof value.category !== 'string' || !value.category.trim() || typeof value.manufacturer !== 'string' || typeof value.quantity !== 'number' || !Number.isInteger(value.quantity) || value.quantity < 1 || typeof value.status !== 'string' || !value.status.trim() || typeof value.description !== 'string' || typeof value.notes !== 'string' || !isRecord(value.purchase) || !isRecord(value.arrival) || !isRecord(value.afterSales) || !Array.isArray(value.images) || !value.images.every(image => { try { validateImage(image); return true; } catch { return false; } })) return false; if (value.purchase.price !== undefined && (typeof value.purchase.price !== 'number' || !Number.isFinite(value.purchase.price) || value.purchase.price < 0)) return false; for (const field of ['currency', 'platform', 'date']) if (value.purchase[field] !== undefined && typeof value.purchase[field] !== 'string') return false; for (const field of ['expectedDate', 'receivedDate']) if (value.arrival[field] !== undefined && value.arrival[field] !== null && typeof value.arrival[field] !== 'string') return false; for (const field of ['status', 'note']) if (value.afterSales[field] !== undefined && typeof value.afterSales[field] !== 'string') return false; const imageIds = new Set<string>(); for (const image of value.images as Array<Record<string, unknown>>) { if (imageIds.has(image.id as string)) return false; imageIds.add(image.id as string); } if (value.workName !== undefined && typeof value.workName !== 'string') return false; return true; }
function validateWork(value: unknown): value is Work { if (!isRecord(value) || typeof value.id !== 'string' || !value.id.trim() || typeof value.name !== 'string' || typeof value.code !== 'string' || !value.code.trim() || !Array.isArray(value.items) || !value.items.every(validateItem)) return false; return value.items.every(item => item.workId === value.id); }
function validateShipping(value: unknown): boolean { return isRecord(value) && typeof value.id === 'string' && value.id.trim() !== '' && typeof value.amount === 'number' && Number.isFinite(value.amount) && value.amount >= 0 && typeof value.currency === 'string' && value.currency.trim() !== '' && (value.date === undefined || typeof value.date === 'string') && (value.carrier === undefined || typeof value.carrier === 'string') && (value.note === undefined || typeof value.note === 'string') && Array.isArray(value.itemIds) && value.itemIds.length > 0 && value.itemIds.every(itemId => typeof itemId === 'string' && itemId.trim() !== ''); }
function validateShippingList(value: unknown): StoreState['shipping'] { if (!Array.isArray(value)) throw dataError('API 回傳運費資料格式無效。'); const ids = new Set<string>(); for (const record of value) { if (!validateShipping(record)) throw dataError('API 回傳運費資料格式無效。'); const id = (record as { id: string }).id; if (ids.has(id)) throw dataError(`API 回傳運費 ID 重複：${id}`); ids.add(id); } return value as StoreState['shipping']; }
function validateMutationResult(data: unknown): MutationResult { if (!isRecord(data) || typeof data.version !== 'string' || !/^\d+\.\d+\.\d+$/.test(data.version)) throw dataError('API 回傳 mutation 結果格式無效。'); return { version: data.version }; }
function validateData(data: unknown): ApiData { if (!isRecord(data) || typeof data.version !== 'string' || !/^\d+\.\d+\.\d+$/.test(data.version) || !Array.isArray(data.works) || !data.works.every(validateWork) || !Array.isArray(data.shipping) || !data.shipping.every(validateShipping)) throw dataError('API 回傳資料格式無效。'); const itemIds = new Set<string>(); for (const work of data.works as Work[]) for (const item of work.items) { if (itemIds.has(item.id)) throw dataError(`API 回傳 Item ID 重複：${item.id}`); itemIds.add(item.id); } const shipping = validateShippingList(data.shipping); for (const record of shipping) for (const itemId of record.itemIds) if (!itemIds.has(itemId)) throw dataError(`API 回傳 Shipping 關聯不存在的 Item：${itemId}`); return { works: data.works as Work[], version: data.version, shipping }; }
function validateAuthStatus(data: unknown): AuthStatus { if (!data || typeof data !== 'object' || typeof (data as { authenticated?: unknown }).authenticated !== 'boolean') throw dataError('API 驗證狀態格式無效。'); return data as AuthStatus; }
function validateAssetResult(data: unknown): AssetResult { if (!data || typeof data !== 'object') throw dataError('API 回傳圖片資料格式無效。'); const value = data as Partial<AssetResult>; if (typeof value.path !== 'string' || typeof value.replaced !== 'boolean' || typeof value.version !== 'string') throw dataError('API 回傳圖片資料格式無效。'); return value as AssetResult; }
function validateAssetDeleteResult(data: unknown): AssetDeleteResult { if (!data || typeof data !== 'object') throw dataError('API 回傳圖片刪除結果格式無效。'); const value = data as Partial<AssetDeleteResult>; if (typeof value.path !== 'string' || value.deleted !== true || typeof value.version !== 'string') throw dataError('API 回傳圖片刪除結果格式無效。'); return value as AssetDeleteResult; }
async function getStaticShipping(): Promise<StoreState['shipping'] | null> { try { const response = await fetch('./data/shipping.json', { cache: 'no-store' }); if (!response.ok) return null; const payload = await response.json(); if (!isRecord(payload) || payload.schemaVersion !== 1) return null; return validateShippingList(payload.records); } catch { return null; } }
export async function getRemoteData(): Promise<ApiData> { try { const response = await fetch('./data/collection.json', { cache: 'no-store' }); if (response.ok) { const data = validateData(await response.json()); const shipping = await getStaticShipping(); return shipping ? { ...data, shipping } : data; } } catch {} return validateData(await request('/data')); }
export async function putItem(item: Item): Promise<ApiData> { validateMutationResult(await request(`/items/${encodeURIComponent(item.id)}`, { method: 'PUT', body: JSON.stringify({ item: toStorageItem(item) }) })); return getRemoteData(); }
export async function deleteItem(id: string): Promise<ApiData> { validateMutationResult(await request(`/items/${encodeURIComponent(id)}`, { method: 'DELETE' })); return getRemoteData(); }
export async function createWork(input: WorkPayload): Promise<ApiData> { return validateData(await request('/works', { method: 'POST', body: JSON.stringify({ work: input }) })); }
export async function updateWork(id: string, input: Omit<WorkPayload, 'id'>): Promise<ApiData> { return validateData(await request(`/works/${encodeURIComponent(id)}`, { method: 'PUT', body: JSON.stringify({ work: input }) })); }
export async function deleteWork(id: string): Promise<ApiData> { return validateData(await request(`/works/${encodeURIComponent(id)}`, { method: 'DELETE' })); }
export async function getAsset(path: string): Promise<Blob> { const headers = new Headers({ Accept: 'image/*' }); const token = authToken(); if (token) headers.set('Authorization', `Bearer ${token}`); const controller = new AbortController(); const timer = window.setTimeout(() => controller.abort(), API_TIMEOUT_MS); try { const response = await fetch(endpoint(`/assets/${path.split('/').map(encodeURIComponent).join('/')}`), { headers, cache: 'no-store', signal: controller.signal }); if (!response.ok) throw dataError(`圖片讀取失敗（${response.status}）。`); return await response.blob(); } catch (error) { if (error instanceof DOMException && error.name === 'AbortError') throw dataError('圖片請求逾時，請稍後再試。'); throw error; } finally { window.clearTimeout(timer); } }
export async function putAsset(path: string, content: string): Promise<AssetResult> { return validateAssetResult(await request(`/assets/${path.split('/').map(encodeURIComponent).join('/')}`, { method: 'PUT', body: JSON.stringify({ path, content }) })); }
export async function deleteAsset(path: string): Promise<AssetDeleteResult> { return validateAssetDeleteResult(await request(`/assets/${path.split('/').map(encodeURIComponent).join('/')}`, { method: 'DELETE' })); }
export async function getShipping(): Promise<StoreState['shipping']> { const data = await request('/shipping'); if (!Array.isArray(data) || !data.every(validateShipping)) throw dataError('API 回傳運費資料格式無效。'); return data as StoreState['shipping']; }
export async function putShipping(record: StoreState['shipping'][number]): Promise<ApiData> { return validateData(await request(`/shipping/${encodeURIComponent(record.id)}`, { method: 'PUT', body: JSON.stringify({ shipping: record }) })); }
export async function deleteShipping(id: string): Promise<ApiData> { return validateData(await request(`/shipping/${encodeURIComponent(id)}`, { method: 'DELETE' })); }
export async function getAuthStatus(): Promise<AuthStatus> { return validateAuthStatus(await request('/auth/status')); }
export function hasAdminSecret(): boolean { return Boolean(authToken()); }
export function setAdminSecret(value: string): void { try { if (value.trim()) sessionStorage.setItem('merch-admin-secret', value.trim()); else sessionStorage.removeItem('merch-admin-secret'); } catch { throw dataError('無法儲存管理驗證資訊。'); } }
export function clearAdminSecret(): void { try { sessionStorage.removeItem('merch-admin-secret'); } catch {} }
export function apiConfigured(): boolean { return Boolean(API_BASE); }
