import './style.css';

type Status = 'received' | 'pending' | 'preorder' | 'cancelled';
interface ImageItem { id: string; url: string; alt: string; isCover?: boolean }
interface Item { id:string; workId:string; title:string; series:string; characters:string[]; category:string; manufacturer:string; status:Status; description:string; notes:string; images:ImageItem[]; purchase:{price:number;currency:string;platform:string;date:string;url:string;orderId:string}; release:{date:string;expectedDate:string;receivedDate:string}; shipping:{status:string;method:string;trackingNumber:string;note:string}; afterSales:{status:string;note:string;updatedAt:string}; createdAt:string; updatedAt:string }
interface Work { id:string; name:string }
interface DB { schemaVersion:number; meta:{updatedAt:string;currency:string}; works:Work[]; items:Item[] }
type Page='home'|'collection'|'statistics'|'management'|'settings'|'item';

const db:DB={schemaVersion:1,meta:{updatedAt:'2026-09-04T10:33:41.220Z',currency:'TWD'},works:[
{id:'honkai-star-rail',name:'崩壞：星穹鐵道'},{id:'genshin-impact',name:'原神'},{id:'zenless-zone-zero',name:'絕區零'},{id:'wuthering-waves',name:'鳴潮'}],items:[
{id:'item-1788499886180-xm1w0h',workId:'honkai-star-rail',title:'流螢 春日手信 1/8比例手辦',series:'',characters:['流螢'],category:'手辦',manufacturer:'Myethos',status:'received',description:'',notes:'',images:[{id:'image-1788513731019-sfc19z',url:'https://raw.githubusercontent.com/tsai97216/merch/main/data/honkai-star-rail/images/item-1788499886180-xm1w0h/image-1788513731019-sfc19z.jpg',alt:'流螢 春日手信 1/8比例手辦',isCover:true}],purchase:{price:1375,currency:'TWD',platform:'米哈遊淘寶',date:'2026-08-05',url:'',orderId:''},release:{date:'',expectedDate:'',receivedDate:'2026-09-14'},shipping:{status:'received',method:'集運',trackingNumber:'',note:''},afterSales:{status:'pending',note:'待換貨',updatedAt:'2026-09-04T05:31:26.180Z'},createdAt:'2026-09-04T05:31:26.180Z',updatedAt:'2026-09-04T09:22:14.136Z'},
{id:'item-1788500327137-hn6eyk',workId:'honkai-star-rail',title:'流螢 春日手信 手辦 訂金卡',series:'',characters:['流螢'],category:'訂金卡',manufacturer:'米哈遊',status:'pending',description:'',notes:'',images:[],purchase:{price:0,currency:'TWD',platform:'米哈遊淘寶',date:'2026-02-27',url:'',orderId:''},release:{date:'',expectedDate:'',receivedDate:''},shipping:{status:'pending',method:'集運',trackingNumber:'',note:''},afterSales:{status:'none',note:'',updatedAt:'2026-09-04T05:38:47.137Z'},createdAt:'2026-09-04T05:38:47.137Z',updatedAt:'2026-09-04T05:38:47.137Z'},
{id:'item-1788517921359-cozvvv',workId:'honkai-star-rail',title:'仲夏螢火之約系列亞克力合影卡',series:'',characters:['流螢'],category:'壓克力',manufacturer:'米哈遊',status:'pending',description:'',notes:'',images:[],purchase:{price:0,currency:'TWD',platform:'米哈遊淘寶',date:'',url:'',orderId:''},release:{date:'',expectedDate:'',receivedDate:''},shipping:{status:'pending',method:'集運',trackingNumber:'',note:''},afterSales:{status:'none',note:'',updatedAt:'2026-09-04T10:33:39.814Z'},createdAt:'2026-09-04T10:32:01.359Z',updatedAt:'2026-09-04T10:33:39.814Z'},
{id:'item-1788499604827-8xrmwb',workId:'zenless-zone-zero',title:'蕾米埃爾 影畫系列 吧唧',series:'',characters:['蕾米埃爾'],category:'吧唧',manufacturer:'米哈遊',status:'preorder',description:'',notes:'',images:[{id:'image-1788517269456-b9dv5w',url:'https://raw.githubusercontent.com/tsai97216/merch/main/data/zenless-zone-zero/images/item-1788499604827-8xrmwb/image-1788517269456-b9dv5w.jpg',alt:'蕾米埃爾 影畫系列 吧唧',isCover:true}],purchase:{price:77,currency:'TWD',platform:'米哈遊淘寶',date:'2026-09-03',url:'',orderId:''},release:{date:'',expectedDate:'2026-11-30',receivedDate:''},shipping:{status:'pending',method:'集運',trackingNumber:'',note:''},afterSales:{status:'none',note:'',updatedAt:'2026-09-04T05:32:09.119Z'},createdAt:'2026-09-04T05:26:44.826Z',updatedAt:'2026-09-04T10:21:12.272Z'}]};

const esc=(v:unknown)=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]??c));
const money=(n:number)=>n.toLocaleString('zh-TW',{style:'currency',currency:'TWD',maximumFractionDigits:0});
const statusText=(s:Status)=>({received:'已到貨',pending:'待到貨',preorder:'預購',cancelled:'已取消'}[s]);
const workName=(id:string)=>db.works.find(w=>w.id===id)?.name??id;
let viewMode:'cards'|'list'=localStorage.getItem('merch:view')==='list'?'list':'cards';
let searchText='',filterWork='all',filterStatus:Status|'all'='all',sortMode='created';

function route():{page:Page;id?:string}{const p=(location.hash.replace(/^#/,'')||'/home').split('/').filter(Boolean);if(p.length===1&&['home','collection','statistics','management','settings'].includes(p[0]))return{page:p[0] as Page};if(p.length===2&&p[0]==='item'){try{return{page:'item',id:decodeURIComponent(p[1])}}catch{return{page:'item',id:''}}}return{page:'home'}}
function header(k:string,t:string,d=''){return `<div class="page-heading"><div><span class="eyebrow">${esc(k)}</span><h2>${esc(t)}</h2>${d?`<p>${esc(d)}</p>`:''}</div></div>`}
function card(i:Item){const im=i.images.find(x=>x.isCover)??i.images[0];return `<article class="item-card"><button class="item-image" data-open="${esc(i.id)}">${im?`<img src="${esc(im.url)}" alt="${esc(im.alt||i.title)}" loading="lazy">`:'<span>NO IMAGE</span>'}</button><button class="item-title" data-open="${esc(i.id)}"><h4>${esc(i.title)}</h4></button><p>${esc(workName(i.workId))} · ${esc(i.characters.join('、'))}</p><div class="item-bottom"><b>${money(i.purchase.price)}</b><span class="tag ${i.status}">${statusText(i.status)}</span></div></article>`}
function filtered(){const q=searchText.trim().toLowerCase();return [...db.items].filter(i=>(filterWork==='all'||i.workId===filterWork)&&(filterStatus==='all'||i.status===filterStatus)&&(!q||[i.title,workName(i.workId),i.characters.join(' '),i.category,i.manufacturer,i.notes].join(' ').toLowerCase().includes(q))).sort((a,b)=>sortMode==='price'?b.purchase.price-a.purchase.price:sortMode==='title'?a.title.localeCompare(b.title,'zh-Hant'):b.createdAt.localeCompare(a.createdAt))}
function home(){const total=db.items.length,received=db.items.filter(i=>i.status==='received').length,pending=total-received,spent=db.items.reduce((s,i)=>s+i.purchase.price,0);return `<section class="page"><div class="hero"><div><span class="eyebrow">01 / HOME</span><h2>我的收藏<br><em>Collection.</em></h2></div><p>收藏資料庫的總覽入口。<br>所有資料集中管理。</p></div><div class="stat-grid">${[['總收藏',total,'ITEMS'],['已到貨',received,'RECEIVED'],['待到貨',pending,'PENDING'],['總花費',money(spent),'TOTAL']].map(x=>`<article class="stat-card"><span>${x[2]}</span><strong>${x[1]}</strong><small>${x[0]}</small></article>`).join('')}</div><div class="two-column"><section class="panel"><div class="panel-heading"><div><span class="panel-label">BY WORK</span><h3>作品分布</h3></div></div>${db.works.map(w=>{const n=db.items.filter(i=>i.workId===w.id).length;return n?`<div class="bar-row"><div><span>${esc(w.name)}</span><b>${n}</b></div><i style="width:${Math.max(8,n/total*100)}%"></i></div>`:''}).join('')||'<div class="empty-state">尚無資料</div>'}</section><section class="panel"><div class="panel-heading"><div><span class="panel-label">STATUS</span><h3>收藏狀態</h3></div></div>${(['received','pending','preorder','cancelled'] as Status[]).map(s=>`<div class="stat-line"><span>${statusText(s)}</span><b>${db.items.filter(i=>i.status===s).length}</b></div>`).join('')}</section></div><section class="section"><div class="section-heading"><div><span class="panel-label">RECENT</span><h3>最近收藏</h3></div><a href="#/collection">查看全部 →</a></div><div class="card-grid">${[...db.items].sort((a,b)=>b.createdAt.localeCompare(a.createdAt)).slice(0,4).map(card).join('')}</div></section></section>`}
function collection(){const list=filtered();return `<section class="page">${header('02 / COLLECTION','收藏')}<div class="collection-tools"><label class="input"><span>⌕</span><input id="search" value="${esc(searchText)}" placeholder="搜尋標題、作品、角色、備註…"></label><select id="work"><option value="all">全部作品</option>${db.works.map(w=>`<option value="${w.id}" ${filterWork===w.id?'selected':''}>${esc(w.name)}</option>`).join('')}</select><select id="status"><option value="all">全部狀態</option>${(['received','pending','preorder','cancelled'] as Status[]).map(s=>`<option value="${s}" ${filterStatus===s?'selected':''}>${statusText(s)}</option>`).join('')}</select></div><div class="collection-meta"><span>${list.length} ITEMS</span><div class="collection-actions"><select id="sort"><option value="created" ${sortMode==='created'?'selected':''}>排序：建立時間</option><option value="title" ${sortMode==='title'?'selected':''}>排序：名稱</option><option value="price" ${sortMode==='price'?'selected':''}>排序：價格</option></select><div class="view-switch"><button class="view-button ${viewMode==='cards'?'is-active':''}" data-view="cards">▦ 卡片</button><button class="view-button ${viewMode==='list'?'is-active':''}" data-view="list">☷ 清單</button></div></div></div>${viewMode==='cards'?`<div class="card-grid collection-grid">${list.length?list.map(card).join(''):'<div class="empty-state full">找不到符合條件的收藏。</div>'}</div>`:`<div class="collection-list">${list.map(i=>`<button class="list-row" data-open="${esc(i.id)}"><span class="list-thumb">${i.images[0]?`<img src="${esc(i.images[0].url)}" alt="">`:'NO IMAGE'}</span><span><strong>${esc(i.title)}</strong><small>${esc(workName(i.workId))} · ${esc(i.category)} · ${esc(i.characters.join('、'))}</small></span><b>${money(i.purchase.price)}</b><span class="tag ${i.status}">${statusText(i.status)}</span></button>`).join('')||'<div class="empty-state">找不到符合條件的收藏。</div>'}</div>`}</section>`}
function detail(id:string){const i=db.items.find(x=>x.id===id);if(!i)return `<section class="page">${header('ITEM DETAIL','找不到收藏')}<div class="panel empty-state">這筆收藏不存在或已被移除。<br><a href="#/collection">返回收藏</a></div></section>`;const im=i.images.find(x=>x.isCover)??i.images[0];const row=(k:string,v:string)=>`<dt>${esc(k)}</dt><dd>${esc(v||'未設定')}</dd>`;return `<section class="page">${header('ITEM DETAIL','收藏詳情',workName(i.workId))}<div class="detail-layout"><div class="detail-image">${im?`<img src="${esc(im.url)}" alt="${esc(im.alt||i.title)}">`:'NO IMAGE'}</div><div class="panel detail-panel"><span class="tag ${i.status}">${statusText(i.status)}</span><h3>${esc(i.title)}</h3><p class="muted">${esc(i.characters.join('、'))} · ${esc(i.category)} · ${esc(i.manufacturer)}</p><div class="detail-price">${money(i.purchase.price)}</div><dl class="details">${row('作品',workName(i.workId))}${row('系列',i.series)}${row('購買平台',i.purchase.platform)}${row('購買日期',i.purchase.date)}${row('預計到貨',i.release.expectedDate)}${row('物流方式',i.shipping.method)}${row('售後',i.afterSales.note)}</dl><div class="detail-actions"><a class="button" href="#/collection">返回</a></div></div></div></section>`}
function statistics(){const spent=db.items.reduce((s,i)=>s+i.purchase.price,0);return `<section class="page">${header('03 / STATISTICS','統計')}<div class="stat-grid"><article class="stat-card"><span>TOTAL ITEMS</span><strong>${db.items.length}</strong><small>總收藏</small></article><article class="stat-card"><span>TOTAL SPENDING</span><strong>${money(spent)}</strong><small>總花費</small></article><article class="stat-card"><span>RECEIVED</span><strong>${db.items.filter(i=>i.status==='received').length}</strong><small>已到貨</small></article><article class="stat-card"><span>PENDING</span><strong>${db.items.filter(i=>i.status!=='received').length}</strong><small>待到貨</small></article></div><div class="two-column"><section class="panel"><div class="panel-heading"><div><span class="panel-label">BY WORK</span><h3>作品</h3></div></div>${db.works.map(w=>{const xs=db.items.filter(i=>i.workId===w.id);return xs.length?`<div class="stat-line"><span>${esc(w.name)}</span><b>${xs.length} · ${money(xs.reduce((s,i)=>s+i.purchase.price,0))}</b></div>`:''}).join('')||'<div class="empty-state">尚無資料</div>'}</section><section class="panel"><div class="panel-heading"><div><span class="panel-label">BY CATEGORY</span><h3>類別</h3></div></div>${[...new Set(db.items.map(i=>i.category))].map(c=>`<div class="stat-line"><span>${esc(c)}</span><b>${db.items.filter(i=>i.category===c).length}</b></div>`).join('')}</section></div></section>`}
function management(){return `<section class="page">${header('04 / MANAGEMENT','管理')}<div class="notice">目前先提供收藏資料檢視。GitHub 寫入與完整 CRUD 會在後續 Data Layer / Worker 階段接入。</div><section class="panel"><div class="panel-heading"><div><span class="panel-label">ITEMS</span><h3>收藏管理</h3></div></div>${db.items.map(i=>`<div class="manage-row"><div><strong>${esc(i.title)}</strong><small>${esc(workName(i.workId))} · ${statusText(i.status)}</small></div><div><a class="button" href="#/item/${encodeURIComponent(i.id)}">查看</a></div></div>`).join('')}</section></section>`}
function settings(){return `<section class="page">${header('05 / SETTINGS','設定')}<section class="panel"><div class="panel-heading"><div><span class="panel-label">SYSTEM</span><h3>系統資訊</h3></div></div><dl class="details"><dt>版本</dt><dd>1.0.0</dd><dt>Schema</dt><dd>${db.schemaVersion}</dd><dt>收藏</dt><dd>${db.items.length}</dd><dt>作品</dt><dd>${db.works.length}</dd></dl></section></section>`}
function render(){const c=document.querySelector<HTMLDivElement>('#content');if(!c)return;const r=route();c.innerHTML=r.page==='home'?home():r.page==='collection'?collection():r.page==='statistics'?statistics():r.page==='management'?management():r.page==='settings'?settings():detail(r.id??'');document.querySelectorAll<HTMLElement>('.nav-item').forEach(e=>e.classList.toggle('active',e.dataset.page===r.page));bind()}
function bind(){document.querySelectorAll<HTMLElement>('[data-open]').forEach(e=>e.addEventListener('click',()=>{location.hash=`#/item/${encodeURIComponent(e.dataset.open??'')}`}));document.querySelectorAll<HTMLButtonElement>('[data-view]').forEach(e=>e.addEventListener('click',()=>{const m=e.dataset.view;if(m==='cards'||m==='list'){viewMode=m;localStorage.setItem('merch:view',m);render()}}));const s=document.querySelector<HTMLInputElement>('#search');if(s)s.addEventListener('input',()=>{searchText=s.value;render();requestAnimationFrame(()=>{const x=document.querySelector<HTMLInputElement>('#search');x?.focus();x?.setSelectionRange(searchText.length,searchText.length)})});const w=document.querySelector<HTMLSelectElement>('#work');if(w)w.addEventListener('change',()=>{filterWork=w.value;render()});const st=document.querySelector<HTMLSelectElement>('#status');if(st)st.addEventListener('change',()=>{filterStatus=st.value as Status|'all';render()});const so=document.querySelector<HTMLSelectElement>('#sort');if(so)so.addEventListener('change',()=>{sortMode=so.value;render()})}
function boot(){try{const app=document.querySelector('#app');if(!app)throw new Error('Missing #app');app.innerHTML=`<div class="site-shell"><aside class="sidebar"><div class="brand"><div class="brand-mark">CM</div><div class="brand-copy"><strong>Chi MERCH</strong><span>Personal Collection</span></div></div><nav class="nav"><a class="nav-item" data-page="home" href="#/home"><i>⌂</i><span>首頁</span></a><a class="nav-item" data-page="collection" href="#/collection"><i>▦</i><span>收藏</span></a><a class="nav-item" data-page="statistics" href="#/statistics"><i>▥</i><span>統計</span></a><a class="nav-item" data-page="management" href="#/management"><i>✎</i><span>管理</span></a><a class="nav-item" data-page="settings" href="#/settings"><i>⚙</i><span>設定</span></a></nav><div class="sidebar-footer"><span>MERCH DATABASE</span><span>v1.0.0</span></div></aside><main class="main"><div class="content" id="content"></div><footer class="footer"><span>Chi MERCH</span><span>Personal Collection Database</span><span>v1.0.0</span></footer></main></div>`;render()}catch(e){console.error(e);const app=document.querySelector('#app');if(app)app.innerHTML='<div class="noscript">收藏庫啟動失敗，請重新整理頁面。</div>'}}
window.addEventListener('hashchange',render);window.addEventListener('DOMContentLoaded',boot);
