import './styles.css';
import { navigate, parseRoute, startRouter, type Route } from './router.ts';
import { store } from './store.ts';
import type { AppState, MerchItem } from './types.ts';
import { formatCurrency, formatCount, formatList } from './utils/format.ts';
import { formatDate, toTimestamp } from './utils/date.ts';

const mount = document.querySelector<HTMLElement>('#app');
if (!mount) throw new Error('找不到 #app');
const root = mount;
let route: Route = parseRoute();
const statusText: Record<string,string> = { received:'已收到', pending:'待處理', preorder:'預購中' };
const statusClass = (s:string) => s==='received'?'received':s==='preorder'?'preorder':s==='pending'?'pending':'';
const label = (s:string) => statusText[s] ?? (s || '未設定');
const money = (i:MerchItem) => formatCurrency(i.purchase.price,i.purchase.currency||'TWD');
const workName = (state:AppState,id:string) => state.works.find(w=>w.id===id)?.name ?? id;
function n<K extends keyof HTMLElementTagNameMap>(tag:K,value?:string,className?:string):HTMLElementTagNameMap[K]{const x=document.createElement(tag);if(className)x.className=className;if(value!==undefined)x.textContent=value;return x;}
function a(text:string,href:string,cls='button'){const x=n('a',text,cls);x.href=href;return x;}
function cover(item:MerchItem):HTMLElement{const box=n('div',undefined,'item-cover');const asset=item.images.find(x=>x.isCover)??item.images[0];if(!asset?.url){box.textContent='NO IMAGE';return box;}const img=n('img') as HTMLImageElement;img.src=asset.url;img.alt=asset.alt||item.title;img.loading='lazy';img.onerror=()=>{img.remove();box.textContent='IMAGE UNAVAILABLE';};box.append(img);return box;}
function shell(state:AppState,title:string,desc:string,content:HTMLElement):HTMLElement{const s=n('div',undefined,'site-shell');const aside=n('aside',undefined,'sidebar');aside.append(a('CHI','#/','brand brand-mark'));const nav=n('nav',undefined,'nav');for(const [name,text] of [['home','首頁'],['collection','收藏'],['statistics','統計'],['management','管理'],['settings','設定']] as const)nav.append(a(text,`#/${name}`,`nav-item${route.name===name?' active':''}`));aside.append(nav,n('footer',`v${state.version?.version??'—'}`,'sidebar-footer'));const main=n('div',undefined,'main');const h=n('header',undefined,'header');h.append(n('p','CHI MERCH','eyebrow'),n('h1',title),n('p',desc));main.append(h,content);s.append(aside,main);return s;}
function statePage(title:string,msg:string,retry=false){const p=n('main',undefined,'state-screen');const c=n('section',undefined,'state-copy');c.append(n('p','CHI MERCH','eyebrow'),n('h1',title),n('p',msg));if(retry){const b=n('button','重新載入','button primary');b.type='button';b.dataset.action='retry';c.append(b);}p.append(c);return p;}
function card(item:MerchItem,state:AppState){const c=n('article',undefined,'item-card');c.tabIndex=0;c.dataset.action='open-item';c.dataset.itemId=item.id;c.append(cover(item));const body=n('div',undefined,'item-card-body');const meta=n('div',undefined,'item-meta');meta.append(n('span',workName(state,item.workId),'item-work'),n('span',label(item.status),`badge ${statusClass(item.status)}`));body.append(meta,n('h3',item.title));const d=[formatList(item.characters),item.category,item.manufacturer].filter(Boolean).join(' · ');if(d)body.append(n('p',d));const bottom=n('div',undefined,'item-bottom');bottom.append(n('b',money(item)),n('span',item.release.expectedDate?`預計 ${formatDate(item.release.expectedDate)`:''));body.append(bottom);c.append(body);return c;}
function filtered(state:AppState){const u=state.ui.collection;const q=u.search.trim().toLocaleLowerCase('zh-TW');return [...state.items].filter(i=>{const hay=[i.title,i.series,i.category,i.manufacturer,i.workId,...i.characters].join(' ').toLocaleLowerCase('zh-TW');return(!q||hay.includes(q))&&(!u.status||i.status===u.status)&&(!u.category||i.category===u.category)&&(!u.character||i.characters.includes(u.character))&&(!u.manufacturer||i.manufacturer===u.manufacturer)&&(!u.workId||i.workId===u.workId);}).sort((x,y)=>u.sort==='price-asc'?x.purchase.price-y.purchase.price:u.sort==='price-desc'?y.purchase.price-x.purchase.price:u.sort==='title-asc'?x.title.localeCompare(y.title,'zh-Hant'):(u.sort==='updated-asc'?1:-1)*(toTimestamp(x.updatedAt)-toTimestamp(y.updatedAt)));}
function home(state:AppState){const p=n('main',undefined,'content page-content');const hero=n('section',undefined,'hero');const copy=n('div',undefined,'hero-copy');copy.append(n('p','COLLECTION','eyebrow'),n('h2','收藏管理系統'),n('p','集中管理收藏、發售、物流與售後資訊。'));hero.append(copy);p.append(hero);const sg=n('div',undefined,'stat-grid');for(const [x,y,z] of [['總收藏',formatCount(state.items.length),'所有資料'],['已收到',formatCount(state.items.filter(i=>i.status==='received').length),'已完成到貨'],['預購中',formatCount(state.items.filter(i=>i.status==='preorder').length),'等待發售'],['待處理',formatCount(state.items.filter(i=>i.status==='pending').length),'需要留意']]){const c=n('article',undefined,'stat-card');c.append(n('span',x),n('strong',y),n('small',z));sg.append(c);}p.append(sg);const grid=n('div',undefined,'two-column');const works=n('section',undefined,'panel');works.append(n('h3','作品'));for(const w of state.works)works.append(a(w.name,'#/collection','simple-list-row'));const recent=n('section',undefined,'panel');recent.append(n('h3','最近更新'));for(const i of [...state.items].sort((x,y)=>toTimestamp(y.updatedAt)-toTimestamp(x.updatedAt)).slice(0,5))recent.append(a(i.title,`#/item/${encodeURIComponent(i.id)}`,'simple-list-row'));grid.append(works,recent);p.append(grid);return shell(state,'我的收藏','收藏管理系統',p);}
function collection(state:AppState){const p=n('main',undefined,'content page-content');const hd=n('div',undefined,'page-heading');const left=n('div');left.append(n('p','COLLECTION','eyebrow'),n('h2','收藏'),n('p',`共 ${formatCount(state.items.length)}。`));hd.append(left);p.append(hd);const panel=n('section',undefined,'panel');const tb=n('div',undefined,'toolbar');const search=n('input') as HTMLInputElement;search.type='search';search.placeholder='搜尋標題、角色、作品、廠商…';search.value=state.ui.collection.search;search.dataset.collectionField='search';tb.append(search);const sel=(field:string,vals:string[],cur:string,all:string)=>{const s=n('select') as HTMLSelectElement;s.dataset.collectionField=field;s.append(new Option(all,''));for(const v of vals)s.append(new Option(v,v,false,v===cur));return s;};tb.append(sel('workId',state.works.map(w=>w.id),state.ui.collection.workId,'全部作品'),sel('status',[...new Set(state.items.map(i=>i.status))],state.ui.collection.status,'全部狀態'),sel('category',[...new Set(state.items.map(i=>i.category).filter(Boolean))],state.ui.collection.category,'全部分類'));const meta=n('div',undefined,'collection-meta');meta.append(n('span',`${formatCount(filtered(state).length)} 符合`),sel('sort',['updated-desc','updated-asc','price-desc','price-asc','title-asc'],state.ui.collection.sort,'排序'));panel.append(tb,meta);const grid=n('div',undefined,state.ui.collection.viewMode==='list'?'item-list':'item-grid');for(const i of filtered(state))grid.append(card(i,state));if(!grid.children.length)grid.append(n('p','沒有符合條件的收藏。','empty-copy'));panel.append(grid);p.append(panel);return shell(state,'收藏','瀏覽、搜尋與整理目前收藏。',p);}
function statistics(state:AppState){const p=n('main',undefined,'content page-content');const panel=n('section',undefined,'panel');const total=state.items.reduce((s,i)=>s+(Number.isFinite(i.purchase.price)?i.purchase.price:0),0);panel.append(n('p','STATISTICS','eyebrow'),n('h2','統計'));const grid=n('div',undefined,'stat-grid');for(const [x,y,z] of [['總收藏',formatCount(state.items.length),'全部'],['總支出',formatCurrency(total),'依資料計算']]){const c=n('article',undefined,'stat-card');c.append(n('span',x),n('strong',y),n('small',z));grid.append(c);}panel.append(grid,n('h3','依作品'));const list=n('div',undefined,'simple-list');for(const w of state.works){const items=state.items.filter(i=>i.workId===w.id);list.append(n('div',`${w.name}　${formatCount(items.length)}　${formatCurrency(items.reduce((s,i)=>s+i.purchase.price,0))}`,'simple-list-row'));}panel.append(list);p.append(panel);return shell(state,'統計','快速掌握收藏規模與消費。',p);}
function detail(state:AppState,id:string){const p=n('main',undefined,'content page-content');const item=state.items.find(i=>i.id===id);if(!item){const panel=n('section',undefined,'panel');panel.append(n('h2','找不到收藏'),n('p','這件收藏不存在。'),a('返回收藏','#/collection','button primary'));p.append(panel);return shell(state,'收藏詳細','',p);}const panel=n('section',undefined,'panel');panel.append(n('p','ITEM','eyebrow'),n('h2',item.title));for(const [k,v] of [['作品',workName(state,item.workId)],['狀態',label(item.status)],['分類',item.category||'未設定'],['角色',formatList(item.characters)||'未設定'],['廠商',item.manufacturer||'未設定'],['價格',money(item)],['購買日期',formatDate(item.purchase.date)],['預計發售',formatDate(item.release.expectedDate)],['物流',item.shipping.status||'未設定'],['售後',item.afterSales.status||'未設定']])panel.append(n('p',`${k}：${v}`));if(item.description)panel.append(n('h3','說明'),n('p',item.description));if(item.notes)panel.append(n('h3','備註'),n('p',item.notes));const imgs=n('div',undefined,'image-grid');for(const im of item.images){const b=n('button',undefined,'image-button');b.type='button';b.dataset.action='view-image';b.dataset.imageUrl=im.url;b.dataset.imageAlt=im.alt||item.title;b.append(cover({...item,images:[im]}));imgs.append(b);}panel.append(imgs,a('返回收藏','#/collection','button'));p.append(panel);return shell(state,'收藏詳細','查看單件收藏的完整資訊。',p);}
function placeholder(state:AppState,title:string){const p=n('main',undefined,'content page-content');const panel=n('section',undefined,'panel');panel.append(n('p','CHI MERCH','eyebrow'),n('h2',title),n('p','此區域尚未啟用。'),a('返回首頁','#/','button primary'));p.append(panel);return shell(state,title,'',p);}
function render(){const state=store.getState();if(state.loading){root.replaceChildren(statePage('載入收藏中','正在讀取作品與收藏資料。'));return;}if(state.error){root.replaceChildren(statePage('資料載入失敗',state.error,true));return;}switch(route.name){case 'home':root.replaceChildren(home(state));break;case 'collection':root.replaceChildren(collection(state));break;case 'statistics':root.replaceChildren(statistics(state));break;case 'item':root.replaceChildren(detail(state,route.id));break;case 'management':root.replaceChildren(placeholder(state,'管理'));break;case 'settings':root.replaceChildren(placeholder(state,'設定'));break;default:root.replaceChildren(placeholder(state,'頁面不存在'));}}
root.addEventListener('click',e=>{const t=e.target instanceof Element?e.target.closest<HTMLElement>('[data-action]'):null;if(!t)return;switch(t.dataset.action){case'open-item':if(t.dataset.itemId)navigate({name:'item',id:t.dataset.itemId});break;case'retry':void store.load();break;case'view-image':{const u=t.dataset.imageUrl;if(!u)break;const o=n('div',undefined,'image-modal');const c=n('button','關閉','button');c.type='button';c.dataset.action='close-image';const im=n('img') as HTMLImageElement;im.src=u;im.alt=t.dataset.imageAlt||'收藏圖片';o.append(c,im);document.body.append(o);break;}case'close-image':t.closest('.image-modal')?.remove();break;}});
root.addEventListener('keydown',e=>{if((e.key==='Enter'||e.key===' ')&&e.target instanceof Element){const t=e.target.closest<HTMLElement>('[data-action="open-item"]');if(t?.dataset.itemId){e.preventDefault();navigate({name:'item',id:t.dataset.itemId});}}});
root.addEventListener('input',e=>{if(e.target instanceof HTMLInputElement&&e.target.dataset.collectionField==='search')store.setCollectionUI({search:e.target.value});});
root.addEventListener('change',e=>{const t=e.target;if(!(t instanceof HTMLInputElement||t instanceof HTMLSelectElement))return;const f=t.dataset.collectionField;if(f==='search')store.setCollectionUI({search:t.value});else if(f==='status')store.setCollectionUI({status:t.value});else if(f==='category')store.setCollectionUI({category:t.value});else if(f==='workId')store.setCollectionUI({workId:t.value});else if(f==='sort')store.setCollectionUI({sort:t.value});});
store.subscribe(render);startRouter(r=>{route=r;render();});void store.load();
