import './toast.css';
import './management-images.css';
import { cleanupAssets, putAsset, deleteAsset } from './api';
import { resolveAssetUrl } from './image-source';
import { buildNextItemId } from './item-id';
import { getStore, type MerchStore } from './store';
import type { ImageMeta, Item } from './types';
import { escapeHtml, qs } from './utils/dom';
import { showToast } from './utils/toast';

let storeRef: MerchStore | null = null;
let unsubscribe: (() => void) | null = null;
let selectedId = '';
let pickerWork = '';
let pickerCategory = '';
let pickerSerial = '';
let searchQuery = '';
let creating = false;
let createCategoryCode = 'o';

const categories = [
  ['b', '徽章／吧唧'], ['c', '卡片／訂金卡'], ['d', '立牌／擺件'], ['e', '電子產品'], ['f', '手辦／模型'], ['g', '文具'], ['h', '海報／掛畫／掛軸'], ['k', '掛件／吊飾'], ['l', '文件／資料夾'], ['m', '書籍／漫畫'], ['n', '明信片'], ['p', '毛絨／布偶'], ['q', '鑰匙圈'], ['r', '雷射票'], ['s', '色紙'], ['v', '服飾'], ['w', '餐具／生活用品'], ['y', '特典'], ['o', '其他']
] as const;
const fields: Record<string, (item: Item) => string> = {
  'management-item-id': x => x.id, 'management-work': x => x.workName ?? '', 'management-title': x => x.title, 'management-series': x => x.series ?? '', 'management-characters': x => (x.characters ?? []).join(', '), 'management-category': x => x.category ?? '', 'management-manufacturer': x => x.manufacturer ?? '', 'management-quantity': x => String(x.quantity), 'management-status': x => x.status, 'management-description': x => x.description ?? '', 'management-notes': x => x.notes ?? '', 'management-price': x => x.purchase?.price == null ? '' : String(x.purchase.price), 'management-currency': x => x.purchase?.currency ?? 'TWD', 'management-platform': x => x.purchase?.platform ?? '', 'management-purchase-date': x => x.purchase?.date ?? '', 'management-purchase-url': x => x.purchase?.url ?? '', 'management-order-id': x => x.purchase?.orderId ?? '', 'management-release-date': x => x.release?.date ?? '', 'management-expected-date': x => x.release?.expectedDate ?? '', 'management-received-date': x => x.release?.receivedDate ?? '', 'management-shipping-status': x => x.shipping?.status ?? '', 'management-shipping-method': x => x.shipping?.method ?? '', 'management-shipping-note': x => x.shipping?.note ?? '', 'management-after-sales-status': x => x.afterSales?.status ?? '', 'management-after-sales-note': x => x.afterSales?.note ?? '', 'management-after-sales-updated': x => x.afterSales?.updatedAt ?? '', 'management-created-at': x => x.createdAt ?? '', 'management-updated-at': x => x.updatedAt ?? ''
};
const get = (id: string) => (qs<HTMLInputElement | HTMLTextAreaElement | HTMLSelectElement>(`#${id}`)?.value ?? '').trim();
const allItems = (): Item[] => storeRef?.snapshot.items ?? [];
function workOf(item: Item): string { return item.workName ?? ''; }
function categoryOf(item: Item): string { return item.category ?? '未分類'; }
function serialOf(item: Item): string { return item.id.match(/(\d+)$/)?.[1] ?? ''; }
function pickerValue(item: Item): string { return `${item.id} · ${item.title}`; }
function sortText(a: string, b: string): number { return a.localeCompare(b, 'zh-Hant', { numeric: true }); }
function unique(values: string[]): string[] { return [...new Set(values.filter(Boolean))].sort(sortText); }
function selectedItem(): Item | undefined { return allItems().find(x => x.id === selectedId); }
function blankItem(): Item | undefined { const work = storeRef?.snapshot.works.find(x => x.name === pickerWork) ?? storeRef?.snapshot.works[0]; if (!work) return undefined; const id = buildNextItemId(allItems().map(x => x.id), work.code, createCategoryCode); const category = categories.find(([code]) => code === createCategoryCode)?.[1] ?? '其他'; return { id, workId: work.id, workName: work.name, title: '', category, quantity: 1, status: 'pending', createdAt: new Date().toISOString(), updatedAt: new Date().toISOString() }; }
function fill(item: Item): void { selectedId = item.id; pickerWork = workOf(item); pickerCategory = categoryOf(item); pickerSerial = serialOf(item); Object.entries(fields).forEach(([id, read]) => { const el = qs<HTMLInputElement | HTMLTextAreaElement | HTMLSelectElement>(`#${id}`); if (el) el.value = read(item); }); }
function searchItems(): Item[] { const query = searchQuery.trim().toLocaleLowerCase(); if (!query) return []; return allItems().filter(item => [item.id, item.title, workOf(item), categoryOf(item), item.series, item.manufacturer, ...(item.characters ?? [])].filter(Boolean).join(' ').toLocaleLowerCase().includes(query)).slice(0, 30); }
function pickerItems(): Item[] { return allItems().filter(item => workOf(item) === pickerWork && categoryOf(item) === pickerCategory); }
function renderSearchResults(): void { const results = searchItems(); const datalist = qs<HTMLDataListElement>('#management-search-options'); if (datalist) datalist.innerHTML = results.map(x => `<option value="${escapeHtml(pickerValue(x))}"></option>`).join(''); const count = qs<HTMLElement>('#management-search-count'); if (count) count.textContent = searchQuery ? `找到 ${results.length} 筆` : `共 ${allItems().length} 筆收藏`; }
function readFormItem(base: Item): Item { const characters = get('management-characters').split(',').map(x => x.trim()).filter(Boolean); const priceText = get('management-price'); const purchase = { ...(base.purchase ?? {}), price: priceText ? Number(priceText) : undefined, currency: get('management-currency') || undefined, platform: get('management-platform') || undefined, date: get('management-purchase-date') || undefined, url: get('management-purchase-url') || undefined, orderId: get('management-order-id') || undefined }; const release = { ...(base.release ?? {}), date: get('management-release-date') || undefined, expectedDate: get('management-expected-date') || undefined, receivedDate: get('management-received-date') || undefined }; const shipping = { ...(base.shipping ?? {}), status: get('management-shipping-status') || undefined, method: get('management-shipping-method') || undefined, note: get('management-shipping-note') || undefined }; const afterSales = { ...(base.afterSales ?? {}), status: get('management-after-sales-status') || undefined, note: get('management-after-sales-note') || undefined, updatedAt: get('management-after-sales-updated') || undefined }; return { ...base, title: get('management-title'), series: get('management-series') || undefined, characters: characters.length ? characters : undefined, category: get('management-category') || undefined, manufacturer: get('management-manufacturer') || undefined, quantity: Number(get('management-quantity')), status: get('management-status') || 'pending', description: get('management-description') || undefined, notes: get('management-notes') || undefined, purchase, release, shipping, afterSales, updatedAt: new Date().toISOString() }; }
function validateItem(item: Item): string[] { const errors: string[] = []; if (!item.title.trim()) errors.push('標題為必填欄位。'); if (!Number.isInteger(item.quantity) || item.quantity < 1) errors.push('數量必須是大於等於 1 的整數。'); if (item.purchase?.price !== undefined && (!Number.isFinite(item.purchase.price) || item.purchase.price < 0)) errors.push('價格必須是大於等於 0 的數字。'); if (item.purchase?.url) { try { new URL(item.purchase.url); } catch { errors.push('商品網址格式無效。'); } } return errors; }
function imageList(item: Item): ImageMeta[] { return [...(item.images ?? [])]; }
function imageUrl(image: ImageMeta): string { return resolveAssetUrl(image.url || image.path || ''); }
function renderImages(item: Item): string { const images = imageList(item); if (!images.length) return '<div class="notice">目前沒有圖片。可從下方選擇圖片上傳。</div>'; return images.map((image, index) => `<div class="management-image-row" data-image-id="${escapeHtml(image.id)}"><div class="management-image-preview">${imageUrl(image) ? `<img src="${escapeHtml(imageUrl(image))}" alt="${escapeHtml(image.alt || item.title)}" loading="lazy">` : '<span>無預覽</span>'}</div><div class="management-image-info"><strong>${escapeHtml(image.id)}</strong><small>${escapeHtml(image.path || image.url || '尚未設定路徑')}</small>${image.isCover ? '<span class="badge">封面</span>' : ''}</div><div class="management-image-actions"><label class="button secondary management-image-replace">替換<input type="file" accept="image/*" data-image-action="replace" data-image-index="${index}" hidden></label><button class="button secondary" type="button" data-image-action="cover" data-image-index="${index}" ${image.isCover ? 'disabled' : ''}>設為封面</button><button class="button secondary" type="button" data-image-action="up" data-image-index="${index}" ${index === 0 ? 'disabled' : ''}>上移</button><button class="button secondary" type="button" data-image-action="down" data-image-index="${index}" ${index === images.length - 1 ? 'disabled' : ''}>下移</button><button class="button danger" type="button" data-image-action="delete" data-image-index="${index}">刪除</button></div></div>`).join(''); }
async function fileToBase64(file: File): Promise<string> { return await new Promise((resolve, reject) => { const reader = new FileReader(); reader.onerror = () => reject(new Error('圖片讀取失敗。')); reader.onload = () => { const value = String(reader.result ?? ''); const comma = value.indexOf(','); if (comma < 0) reject(new Error('圖片資料格式無效。')); else resolve(value.slice(comma + 1)); }; reader.readAsDataURL(file); }); }
function imageExtension(file: File): string { const ext = file.name.split('.').pop()?.toLowerCase() || 'jpg'; return ['jpg', 'jpeg', 'png', 'webp', 'gif', 'avif'].includes(ext) ? ext : 'jpg'; }
function imagePath(item: Item, file: File): string { const safeName = file.name.replace(/[^a-zA-Z0-9._-]+/g, '-').replace(/\.[^.]+$/, '').slice(0, 80) || 'image'; return `data/${item.workId}/images/${item.id}/${Date.now()}-${safeName}.${imageExtension(file)}`; }
async function updateImages(item: Item, images: ImageMeta[]): Promise<void> { if (!storeRef) throw new Error('資料庫尚未載入。'); await storeRef.updateItem({ ...item, images, updatedAt: new Date().toISOString() }); }
async function uploadImage(file: File): Promise<void> { const item = selectedItem(); if (!item) { showToast('請先儲存收藏，再上傳圖片。', 'error'); return; } if (!file.type.startsWith('image/')) { showToast('只允許上傳圖片檔案。', 'error'); return; } if (file.size > 8 * 1024 * 1024) { showToast('圖片大小不可超過 8 MB。', 'error'); return; } try { showToast('正在上傳圖片…', 'info'); const uploaded = await putAsset(imagePath(item, file), await fileToBase64(file)); const images = imageList(item); images.push({ id: `${item.id}-${Date.now()}`, path: uploaded.path, url: uploaded.url, sha: uploaded.sha, alt: item.title, isCover: images.length === 0 }); try { await updateImages(item, images); } catch (error) { try { await deleteAsset(uploaded.path); } catch { /* best-effort orphan cleanup */ } throw error; } showToast('圖片已上傳並加入收藏。', 'success'); } catch (error) { showToast(error instanceof Error ? error.message : '圖片上傳失敗。', 'error'); } }
async function replaceImage(file: File, index: number): Promise<void> { const item = selectedItem(); if (!item) { showToast('請先選擇收藏。', 'error'); return; } if (!file.type.startsWith('image/')) { showToast('只允許上傳圖片檔案。', 'error'); return; } if (file.size > 8 * 1024 * 1024) { showToast('圖片大小不可超過 8 MB。', 'error'); return; } const current = imageList(item)[index]; if (!current) return; try { showToast('正在替換圖片…', 'info'); const uploaded = await putAsset(imagePath(item, file), await fileToBase64(file)); const images = imageList(item); images[index] = { ...current, path: uploaded.path, url: uploaded.url, sha: uploaded.sha, alt: current.alt || item.title }; try { await updateImages(item, images); } catch (error) { try { await deleteAsset(uploaded.path); } catch { /* best-effort orphan cleanup */ } throw error; } if (current.path && current.path !== uploaded.path) { try { await deleteAsset(current.path); } catch { showToast('新圖片已套用，但舊圖片清理失敗，之後可由孤兒圖片清理處理。', 'error'); return; } } showToast('圖片已成功替換。', 'success'); } catch (error) { showToast(error instanceof Error ? error.message : '圖片替換失敗。', 'error'); } }
async function mutateImage(action: string, index: number): Promise<void> { const item = selectedItem(); if (!item || !storeRef) return; const images = imageList(item); if (!images[index]) return; if (action === 'delete') { if (!window.confirm(`確定要刪除這張圖片？\n「${item.title}」的圖片檔案也會從遠端移除。`)) return; const target = images[index]; const next = images.filter((_, i) => i !== index); if (next.length && !next.some(x => x.isCover)) next[0] = { ...next[0], isCover: true }; try { await updateImages(item, next); if (target.path) await deleteAsset(target.path); showToast('圖片已刪除。', 'success'); } catch (error) { try { await updateImages(item, images); } catch { /* best-effort metadata recovery */ } showToast(error instanceof Error ? error.message : '圖片刪除失敗。', 'error'); } return; } if (action === 'cover') images.forEach((image, i) => { image.isCover = i === index; }); if (action === 'up' && index > 0) [images[index - 1], images[index]] = [images[index], images[index - 1]]; if (action === 'down' && index < images.length - 1) [images[index + 1], images[index]] = [images[index], images[index + 1]]; try { await updateImages(item, images); showToast(action === 'cover' ? '封面已更新。' : '圖片順序已更新。', 'success'); } catch (error) { showToast(error instanceof Error ? error.message : '圖片更新失敗。', 'error'); } }
async function handleCleanupAssets(): Promise<void> { if (!window.confirm('確定要掃描並刪除未被任何收藏圖片資料引用的孤兒圖片？\n只會處理系統管理的 data/*/images/* 圖片。')) return; const button = qs<HTMLButtonElement>('#management-cleanup-assets'); if (button) button.disabled = true; try { showToast('正在掃描孤兒圖片…', 'info'); const result = await cleanupAssets(); showToast(`清理完成：刪除 ${result.deleted} 張，保留 ${result.kept} 張。`, 'success'); } catch (error) { showToast(error instanceof Error ? error.message : '孤兒圖片清理失敗。', 'error'); } finally { if (button) button.disabled = false; } }
async function saveItem(): Promise<void> { const item = selectedItem(); if (!item || !storeRef) return; const next = readFormItem(item); const errors = validateItem(next); if (errors.length) { showToast(errors.join('\n'), 'error'); return; } try { await storeRef.updateItem(next); showToast('收藏已更新。', 'success'); } catch (error) { showToast(error instanceof Error ? error.message : '收藏更新失敗。', 'error'); } }
async function createItem(): Promise<void> { if (!storeRef) return; const base = blankItem(); if (!base) { showToast('目前沒有可用作品。', 'error'); return; } const item = readFormItem(base); const errors = validateItem(item); if (errors.length) { showToast(errors.join('\n'), 'error'); return; } try { await storeRef.addItem(item); selectedId = item.id; creating = false; showToast('收藏已新增。', 'success'); } catch (error) { showToast(error instanceof Error ? error.message : '收藏新增失敗。', 'error'); } }
function renderManagement(): void { const root = qs<HTMLElement>('#management-root'); if (!root || !storeRef) return; const items = allItems(); const works = storeRef.snapshot.works; const workOptions = works.map(work => `<option value="${escapeHtml(work.name)}"></option>`).join(''); const categoryOptions = categories.map(([code, name]) => `<option value="${escapeHtml(name)}">${escapeHtml(code.toUpperCase())} · ${escapeHtml(name)}</option>`).join(''); const statusOptions = ['pending', 'shipping', 'received', 'cancelled'].map(x => `<option value="${x}">${x}</option>`).join(''); root.innerHTML = `<section class="management-page"><header class="management-header"><div><p class="eyebrow">Management</p><h1>收藏管理</h1><p class="muted">集中管理收藏資料、圖片與遠端 GitHub 儲存內容。</p></div><div class="management-toolbar"><label class="field"><span>搜尋收藏</span><input id="management-search" list="management-search-options" value="${escapeHtml(searchQuery)}" placeholder="ID、名稱、角色、分類…"><datalist id="management-search-options"></datalist></label><button class="button" id="management-new" type="button">新增收藏</button><button class="button secondary" id="management-cleanup-assets" type="button">清理孤兒圖片</button></div></header><div class="management-grid"><aside class="management-browser"><div class="management-picker"><label class="field"><span>作品</span><select id="management-picker-work">${works.map(work => `<option value="${escapeHtml(work.name)}" ${work.name === pickerWork ? 'selected' : ''}>${escapeHtml(work.name)}</option>`).join('')}</select></label><label class="field"><span>分類</span><select id="management-picker-category">${categoryOptions.replace(/<option value="([^"]+)"/g, '<option value="$1"').replace(/ selected/g, '')}</select></label><label class="field"><span>編號</span><select id="management-picker-serial"><option value="">選擇收藏</option>${pickerItems().map(item => `<option value="${escapeHtml(serialOf(item))}" ${serialOf(item) === pickerSerial ? 'selected' : ''}>${escapeHtml(pickerValue(item))}</option>`).join('')}</select></label></div><div id="management-search-count" class="muted management-count"></div><div id="management-list" class="management-list"></div></aside><main class="management-editor">${selectedItem() ? renderEditor(selectedItem()!) : '<div class="empty-state"><h2>選擇一筆收藏</h2><p>從左側選擇收藏，或建立一筆新的收藏資料。</p></div>'}</main></div></section>`; renderSearchResults(); renderList(items); bindManagement(); }
function renderEditor(item: Item): string { const workOptions = storeRef?.snapshot.works.map(work => `<option value="${escapeHtml(work.name)}" ${work.name === item.workName ? 'selected' : ''}>${escapeHtml(work.name)}</option>`).join('') ?? ''; const categoryOptions = categories.map(([code, name]) => `<option value="${escapeHtml(name)}" ${name === item.category ? 'selected' : ''}>${escapeHtml(code.toUpperCase())} · ${escapeHtml(name)}</option>`).join(''); const statusOptions = ['pending', 'shipping', 'received', 'cancelled'].map(x => `<option value="${x}" ${x === item.status ? 'selected' : ''}>${x}</option>`).join(''); return `<div class="management-editor-inner"><div class="management-editor-header"><div><p class="eyebrow">收藏編輯</p><h2>${escapeHtml(item.title || '未命名收藏')}</h2><p class="muted">${escapeHtml(item.id)}</p></div><div class="management-actions"><button class="button" id="management-save" type="button">儲存變更</button><button class="button danger" id="management-delete" type="button">刪除收藏</button></div></div><div class="management-form">...`; }
