import './shipping.css';
import { getStore, type MerchStore } from './store';
import type { Item, ShippingRecord } from './types';
import { escapeHtml, qs } from './utils/dom';
import { showToast } from './utils/toast';

let storeRef: MerchStore | null = null;
let editingId = '';
let saving = false;
const allItems=()=>storeRef?.snapshot.items??[];
const money=(n:number,c:string)=>`${c||'TWD'} ${new Intl.NumberFormat('zh-TW').format(n)}`;
function detail(record:ShippingRecord):void{const items=allItems().filter(item=>record.itemIds.includes(item.id));const modal=document.createElement('div');modal.className='shipping-detail';modal.innerHTML=`<div class="shipping-detail-backdrop" data-shipping-close></div><section class="shipping-detail-dialog" role="dialog" aria-modal="true" aria-labelledby="shipping-detail-title" tabindex="-1"><header class="panel-heading"><div><span class="panel-label">SHIPPING DETAIL</span><h2 id="shipping-detail-title">運費詳情</h2></div><button type="button" class="button secondary" data-shipping-close>關閉</button></header><div class="shipping-detail-grid"><div><span>金額</span><strong>${escapeHtml(money(record.amount,record.currency))}</strong></div><div><span>日期</span><strong>${escapeHtml(record.date||'未填日期')}</strong></div><div><span>物流／平台</span><strong>${escapeHtml(record.carrier||'未設定')}</strong></div><div><span>關聯周邊</span><strong>${record.itemIds.length} 件</strong></div></div>${record.note?`<div class="shipping-detail-note"><span>備註</span><p>${escapeHtml(record.note)}</p></div>`:''}<div class="shipping-detail-items"><h3>關聯周邊</h3>${items.length?`<ul>${items.map(item=>`<li><strong>${escapeHtml(item.id)}</strong><span>${escapeHtml(item.title)}</span></li>`).join('')}</ul>`:'<div class="empty-state">關聯的周邊目前不存在。</div>'}</div></section>`;document.body.appendChild(modal);document.body.classList.add('shipping-detail-open');const close=()=>{modal.remove();document.body.classList.remove('shipping-detail-open');};modal.querySelectorAll<HTMLElement>('[data-shipping-close]').forEach(node=>node.addEventListener('click',close));modal.querySelector<HTMLElement>('.shipping-detail-dialog')?.focus();}
function setValue(id:string,value:string):void{const el=qs<HTMLInputElement|HTMLTextAreaElement|HTMLSelectElement>(`#${id}`);if(el)el.value=value;}
function renderItems(selected:ShippingRecord|undefined):void{const root=qs<HTMLElement>('[data-shipping-items]');if(!root)return;root.innerHTML=allItems().map(i=>`<label class="shipping-item"><input type="checkbox" value="${escapeHtml(i.id)}" ${selected?.itemIds.includes(i.id)?'checked':''} ${saving?'disabled':''}><span>${escapeHtml(i.id)} · ${escapeHtml(i.title)}</span></label>`).join('')||'<span class="muted">目前沒有周邊。</span>';}
function renderRecords():void{const root=qs<HTMLElement>('[data-shipping-records]');if(!root||!storeRef)return;const records=storeRef.snapshot.shipping??[];root.innerHTML=records.length?records.map(r=>`<article class="shipping-card" data-shipping-detail="${escapeHtml(r.id)}"><div><strong>${escapeHtml(money(r.amount,r.currency))}</strong><span>${escapeHtml(r.date||'未填日期')}</span></div><p>${escapeHtml(r.carrier||'未設定物流')}${r.note?` · ${escapeHtml(r.note)}`:''}</p><small>關聯 ${r.itemIds.length} 件周邊</small><div class="shipping-card-actions"><button class="button secondary" type="button" data-shipping-edit="${escapeHtml(r.id)}" ${saving?'disabled':''}>編輯</button><button class="button danger" type="button" data-shipping-delete="${escapeHtml(r.id)}" ${saving?'disabled':''}>刪除</button></div></article>`).join(''):'<div class="empty-state">目前沒有運費紀錄。</div>';}
function render():void{if(!storeRef)return;const records=storeRef.snapshot.shipping??[];const selected=records.find(x=>x.id===editingId);const title=qs<HTMLElement>('[data-shipping-editor-title]');if(title)title.textContent=selected?'編輯運費':'新增運費';setValue('shipping-amount',selected?String(selected.amount):'');setValue('shipping-currency',selected?.currency??'TWD');setValue('shipping-date',selected?.date??'');setValue('shipping-carrier',selected?.carrier??'');setValue('shipping-note',selected?.note??'');const form=qs<HTMLFormElement>('#shipping-form');if(form)form.setAttribute('aria-busy',String(saving));form?.querySelectorAll<HTMLInputElement|HTMLTextAreaElement|HTMLSelectElement>('input,textarea,select').forEach(el=>el.disabled=saving);const submit=qs<HTMLButtonElement>('#shipping-form button[type="submit"]');if(submit){submit.disabled=saving;submit.textContent=saving?'儲存中…':selected?'儲存修改':'新增運費';}const cancel=qs<HTMLButtonElement>('#shipping-cancel');if(cancel){cancel.hidden=!selected;cancel.disabled=saving;}renderItems(selected);renderRecords();}
async function save(e:SubmitEvent){e.preventDefault();if(!storeRef||saving)return;const amount=Number(qs<HTMLInputElement>('#shipping-amount')?.value);const currency=qs<HTMLInputElement>('#shipping-currency')?.value.trim()||'TWD';const itemIds=[...document.querySelectorAll<HTMLInputElement>('#shipping-form input[type="checkbox"]:checked')].map(x=>x.value);if(!Number.isFinite(amount)||amount<0){showToast('請輸入有效的運費金額。','error');return;}if(!itemIds.length){showToast('請至少選擇一個關聯周邊。','error');return;}const record:ShippingRecord={id:editingId||`ship-${Date.now().toString(36)}`,amount,currency,date:qs<HTMLInputElement>('#shipping-date')?.value||undefined,carrier:qs<HTMLInputElement>('#shipping-carrier')?.value.trim()||undefined,note:qs<HTMLTextAreaElement>('#shipping-note')?.value.trim()||undefined,itemIds};saving=true;render();try{await storeRef.saveShipping(record);editingId='';showToast('運費紀錄已儲存。','success');}catch(e){showToast(e instanceof Error?e.message:'儲存運費失敗。','error');}finally{saving=false;render();}}
async function remove(id:string){if(!storeRef||saving)return;saving=true;render();try{await storeRef.deleteShipping(id);if(editingId===id)editingId='';showToast('運費紀錄已刪除。','success');}catch(e){showToast(e instanceof Error?e.message:'刪除運費失敗。','error');}finally{saving=false;render();}}
function bind(){const root=qs<HTMLElement>('#shipping-root');if(!root)return;root.addEventListener('submit',e=>{void save(e as SubmitEvent)});root.addEventListener('click',async e=>{const t=e.target as Element;const edit=t.closest<HTMLElement>('[data-shipping-edit]');if(edit&&!saving){editingId=edit.dataset.shippingEdit||'';render();return}const del=t.closest<HTMLElement>('[data-shipping-delete]');if(del&&!saving){if(confirm('確定刪除此筆運費紀錄？'))await remove(del.dataset.shippingDelete||'');return}const card=t.closest<HTMLElement>('[data-shipping-detail]');if(card&&!t.closest('button')&&!saving){const record=recordsById(card.dataset.shippingDetail||'');if(record)detail(record);return}if(t.closest('#shipping-cancel')&&!saving){editingId='';render();}})}
const recordsById=(id:string)=>storeRef?.snapshot.shipping.find(record=>record.id===id);
async function init(){storeRef=await getStore();storeRef.subscribe(()=>{if(!saving)render()});render();bind()}
void init();
