import type { MerchItem, VersionInfo, Work, WorkData, WorksFile } from './types.ts';
export class DataValidationError extends Error { constructor(message:string){super(message);this.name='DataValidationError';} }
function fail(path:string,message:string):never{throw new DataValidationError(`${path}: ${message}`);}
function isRecord(v:unknown):v is Record<string,unknown>{return typeof v==='object'&&v!==null&&!Array.isArray(v);}
function requireObject(v:unknown,path:string):asserts v is Record<string,unknown>{if(!isRecord(v))fail(path,'必須是物件');}
function requireArray(v:unknown,path:string):asserts v is unknown[]{if(!Array.isArray(v))fail(path,'必須是陣列');}
function requireString(v:unknown,path:string):asserts v is string{if(typeof v!=='string')fail(path,'必須是字串');}
function requireNumber(v:unknown,path:string):asserts v is number{if(typeof v!=='number'||!Number.isFinite(v))fail(path,'必須是有限數字');}
function requireBoolean(v:unknown,path:string):asserts v is boolean{if(typeof v!=='boolean')fail(path,'必須是布林值');}
function validateImage(v:unknown,path:string):void{requireObject(v,path);for(const k of ['id','path','url','sha','alt'])requireString(v[k],`${path}.${k}`);requireBoolean(v.isCover,`${path}.isCover`);}
function validateItem(v:unknown,path:string):asserts v is MerchItem{requireObject(v,path);for(const k of ['id','workId','title','series','category','manufacturer','status','description','notes','createdAt','updatedAt'])requireString(v[k],`${path}.${k}`);requireArray(v.images,`${path}.images`);for(let i=0;i<v.images.length;i++)validateImage(v.images[i],`${path}.images[${i}]`);requireArray(v.characters,`${path}.characters`);for(let i=0;i<v.characters.length;i++)requireString(v.characters[i],`${path}.characters[${i}]`);requireObject(v.purchase,`${path}.purchase`);requireNumber(v.purchase.price,`${path}.purchase.price`);for(const k of ['currency','platform','date','url','orderId'])requireString(v.purchase[k],`${path}.purchase.${k}`);requireObject(v.release,`${path}.release`);for(const k of ['date','expectedDate','receivedDate'])requireString(v.release[k],`${path}.release.${k}`);requireObject(v.shipping,`${path}.shipping`);for(const k of ['status','method','trackingNumber','note'])requireString(v.shipping[k],`${path}.shipping.${k}`);requireObject(v.afterSales,`${path}.afterSales`);for(const k of ['status','note','updatedAt'])requireString(v.afterSales[k],`${path}.afterSales.${k}`);}
export function validateWorksFile(v:unknown):asserts v is WorksFile{requireObject(v,'works.json');requireNumber(v.schemaVersion,'works.json.schemaVersion');requireArray(v.works,'works.json.works');const ids=new Set<string>();for(let i=0;i<v.works.length;i++){const p=`works.json.works[${i}]`;const w=v.works[i];requireObject(w,p);requireString(w.id,`${p}.id`);requireString(w.name,`${p}.name`);requireString(w.data,`${p}.data`);if(ids.has(w.id))fail(`${p}.id`,'工作 ID 重複');ids.add(w.id);}}
export function validateWorkData(v:unknown):asserts v is WorkData{requireObject(v,'work data');requireNumber(v.schemaVersion,'work data.schemaVersion');for(const k of ['work','name','updatedAt'])requireString(v[k],`work data.${k}`);requireArray(v.items,'work data.items');const ids=new Set<string>();for(let i=0;i<v.items.length;i++){const p=`work data.items[${i}]`;const x=v.items[i];validateItem(x,p);if(ids.has(x.id))fail(`${p}.id`,'項目 ID 重複');ids.add(x.id);}}
export function validateVersion(v:unknown):asserts v is VersionInfo{requireObject(v,'version.json');requireString(v.version,'version.json.version');requireString(v.updatedAt,'version.json.updatedAt');if(!/^\d+\.\d+\.\d+$/.test(v.version))fail('version.json.version','版本號格式無效');}
export function validateDataset(works:Work[],items:MerchItem[]):void{const workIds=new Set(works.map(w=>w.id));const itemIds=new Set<string>();for(const item of items){if(!workIds.has(item.workId))fail(`item.${item.id}.workId`,'指向不存在的作品');if(itemIds.has(item.id))fail(`item.${item.id}`,'項目 ID 重複');itemIds.add(item.id);}}
